### ISSUE TITLE
undefined function List.Chars.Vutuv.User.to_char_list/1

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#104]
After registering a new user I get this error:

![bildschirmfoto 2016-08-05 um 14 24 18](https://cloud.githubusercontent.com/assets/69770/17436589/4f2a2f6a-5b18-11e6-870e-cbd15fca3ca7.png)

**Comment by cjfreeze** [comment]
I can't reproduce the error. What fields did you use for the new user?
Additionally, can you confirm the following code is in your User module?

```
defimpl List.Chars, for: Vutuv.User do   
    def to_charlist(user), do: '#{user.first_name} #{user.last_name}'
end
```

**Comment by wintermeyer** [comment]
For the first test I always do a `mix ecto.reset` and use my name and email address to register.

**Comment by cjfreeze** [comment]
A new dependency was added. Did you call mix deps.get?

**Comment by wintermeyer** [comment]
I did a `mix deps.get`. No change. It doesn't work.

**Comment by wintermeyer** [comment]
The code is in the project.

**Comment by cjfreeze** [comment]
Oh I think I see the problem. What version of elixir does elixir -v return?

**Comment by wintermeyer** [comment]
Elixir 1.2.6

**Comment by cjfreeze** [comment]
I think in a recent update they changed the semantics of get_char_list to get_charlist. I'm on 1.3.1.

**Comment by cjfreeze** [comment]
I've amended the Readme to prevent this issue in the future. 274a1ab
