### ISSUE TITLE
no function clause matching in Slugger.replace_chars/1

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#105]
`mix ecto.reset` + `mix phoenix.server` + register a new user =>

![bildschirmfoto 2016-08-05 um 16 03 28](https://cloud.githubusercontent.com/assets/69770/17439031/3df10602-5b26-11e6-8a7a-dfd89a546f98.png)

**Comment by cjfreeze** [comment]
Closed by 3fc2a18.
