### ISSUE TITLE
Add experiences scaffold

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#108]
`experiences` tell the story of a working life. They are nested in `/users/:slug/experiences` and sorted by the `start_at` date.
# Attributes
- organisation:string
- job_title:string
- description:text
- location:string
- start_month:integer
- start_year:integer
- end_month:integer
- end_year:integer
## Validations
- organisation
- job_title
- end (month/year) should be nil or after start (month/year)
# Brainstorming

I'd love to have a real `company` model for this where different `users` can work at the same `company`. So in case you have a good and easy to implement solution for this go for it. Otherwise we'll postpone that to later milestones.

**Comment by cjfreeze** [comment]
I'll implement functionality for companies to be associations of work experiences, it will just be hidden until we implement a company system.
