### ISSUE TITLE
Add social media accounts

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#110]
A `user` has many `social_media_accounts`. They are nested in `/users/:slug/social_media_accounts/`
# Available social media provider

This is tricky. Let's start with these (please add important provider I forgot):
- Facebook
- Twitter
- Instagram
- YouTube
- Snapchat
- Stackoverflow
# Attributes
- provider:string
- account:string
## Validations

This is going to be a wild mix of regex. The user should be able to enter the full url e.g. https://twitter.com/wintermeyer and the validation converts this to @wintermeyer. Obviously if a user enters just @wintermeyer it should be good too.
# Brainstorming

Maybe it makes sense to add a scaffold for `providers` which would become a belongs_to relationship. Fire at will.

**Comment by cjfreeze** [comment]
Would it be easier to combine this model with urls? We could add a "Provider" field or something similar to the URL schema, with preset choices such as Facebook, Twitter, Stackoverflow, etc. and have "other" be an option for personal urls. This is just a thought; as you've said before database fields are cheap so implementing a separate model for social media accounts would not be a bad option.

**Comment by cjfreeze** [comment]
After further thought, it seems like combining them would just create more work than keeping them separate would.
