### ISSUE TITLE
vcard export

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#123]
It should be easy to (read-only) access the user data and the data of his/her followees by an API. We start with these common formats:
- vCard 3.0 (https://en.wikipedia.org/wiki/VCard)

The URL to access this API should start with `/api/v1.0/` and than follows the normal route.

Examples:
- `/api/v1.0/users/:slug.vcard`

**Comment by cjfreeze** [comment]
I'm going to start with jCard, commit, and work on vCard 3.0 later.

I am doing this because Phoenix natively supports JSON encoding, which makes vCard4.0 (jCard) incredibly easy to do, while vCard3.0 is a bit more difficult.

**Comment by wintermeyer** [comment]
http://jsonapi.org/

**Comment by wintermeyer** [comment]
`resources "/vcard"` is wrong. 

JSON should be `/api/1.0/users/stefan.wintermeyer.json`. Please have a look at http://jsonapi.org/ to get an idea. Any developer who uses the normal website should be able to use the API by just knowing the prefix `/api/1.0/`.

`vcard` is just an other file extension within that basic idea. So the `vcard` would be available at `/api/1.0/users/stefan.wintermeyer.vcard`

**Comment by cjfreeze** [comment]
I have implemented the vcard (jcard) export according to http://jsonapi.org/ in commit 27554de. Before I continue to build onto the API let me know if you'd like me to do anything different.

**Comment by wintermeyer** [comment]
The URL is wrong. It shouldn't be `http://localhost:4000/api/1.0/users/stefan.wintermeyer/vcard` but `http://localhost:4000/api/1.0/users/stefan.wintermeyer.vcard` for my account. Plus the `vcard` format is not right yet. A vcard file doesn't use the JSON format. It looks like this:

```
BEGIN:VCARD
VERSION:3.0
N:Gump;Forrest;;Mr.
FN:Forrest Gump
ORG:Bubba Gump Shrimp Co.
TITLE:Shrimp Man
PHOTO;VALUE=URI;TYPE=GIF:http://www.example.com/dir_photos/my_photo.gif
TEL;TYPE=WORK,VOICE:(111) 555-1212
TEL;TYPE=HOME,VOICE:(404) 555-1212
ADR;TYPE=WORK,PREF:;;100 Waters Edge;Baytown;LA;30314;United States of Amer
 ica
LABEL;TYPE=WORK,PREF:100 Waters Edge\nBaytown\, LA 30314\nUnited States of 
 America
ADR;TYPE=HOME:;;42 Plantation St.;Baytown;LA;30314;United States of America
LABEL;TYPE=HOME:42 Plantation St.\nBaytown\, LA 30314\nUnited States of Ame
 rica
EMAIL:forrestgump@example.com
REV:2008-04-24T19:52:43Z
END:VCARD
```
