### ISSUE TITLE
Refactor address model to be internationally compliant

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#124]
The address model needs to be internationally compliant. 

See [here.](http://stackoverflow.com/questions/929684/is-there-common-street-addresses-database-design-for-all-addresses-of-the-world/)

**Comment by cjfreeze** [comment]
The model is finished, but the form requires most of the work. I'm going to include a few example forms (USA, Germany), and create an issue for adding the rest of the forms. I won't be committing the changes until the form part is done.
