### ISSUE TITLE
user_url, user_skill, user_date

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#125]
I'm not happy with the following model names:
- user_url
- user_skill
- user_date

All of them would make sense for `company` too (in the future). Does Ecto support polymorphic associations? If yes we should change these models to `user`, `skill` and `special_date` and make them polymorphic.

**Comment by cjfreeze** [comment]
Url and date can be renamed and made polymorphic. User skill, however, is a join table between user and skills, so its name makes sense to be user_skills. Similarly, when we make the company model, we will make another table named company_skills.
