### ISSUE TITLE
Default language for a user (i18n)

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#126]
The `user` model should have a field `default_language_id` which belongs to a `language` model where all available languages are stored. That language would be used to render the i18n templates. The first too available languages would be English (en) and German (de).

During registration of a new user the system should use the browser [preferred language settings](https://www.w3.org/International/questions/qa-lang-priorities).

Maybe this issue has to be split into sub issues. Fire at will.

**Comment by cjfreeze** [comment]
It seems that there are several tools available to us to internationalize. Gettext offers a i18n feature that I think we should take advantage of. Additionally, language selection is a small issue while translation is a huge issue, so multiple issues are most likely necessary. Finally, offering language selection as an optional part of user settings is in my opinion the best development path, and in all other cases go by the browser preferred locale.

Supported locales would actually be a part of config in this implementation.

See issues #135 and #136.
