### ISSUE TITLE
Create address form templates for all countries with locales we support

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#127]
Some countries might be able to use a generic template, others may require very specific templates. Displaying this information with the correct labels will also be tricky.

**Comment by wintermeyer** [comment]
I'd like to use value from https://github.com/vutuv/vutuv/issues/126 to display the address. That might not be 100% perfect but good enough for a start. So if somebody uses "de" as the language setting we use "de" to display the address too.

**Comment by cjfreeze** [comment]
If that's the case, then we should only make specific address form templates for locales we support, and offer a generic address form template for all other countries.
