### ISSUE TITLE
Most preferred supported locale (i18n)

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#136]
Check all browser locales and cross reference them with all supported locales, then select the most preferred supported locale.

Currently the locale plug takes the most preferred locale regardless of whether it is supported or not.

This is a sub issue of #126.

**Comment by wintermeyer** [comment]
```
[info] GET /
["de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4"]
de-DE
```
