### ISSUE TITLE
vcard export bug

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#141]
A GET request to `http://localhost:4000/api/1.0/users/stefan.wintermeyer.json` results ins a 
`function Vutuv.Api.UserController.show/2 is undefined or private`
![bildschirmfoto 2016-09-13 um 09 31 39](https://cloud.githubusercontent.com/assets/69770/18465068/05de1b6e-7995-11e6-93ff-aa4ebb04340b.png)

**Comment by cjfreeze** [comment]
The .json feature is not yet implemented. To get the vcard, you'll need to get request `users/<slug>/vcard`. See issue #142
