### ISSUE TITLE
Create a search_query scaffold

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#144]
The `search_query` model has the following fields:
- `value` = string
- `is_email_address` = boolean
## Validations

During validation the `is_email_address` is set to `true` if `value` has the correct format of an email address. In that case `value` is stored lowercased.

`value` should be unique. I don't know what is the best way to do this. I want to have a history to a specific search `value`. If many people search for `alice@example.com` than this `user` must be more important than other users.
## Associations
- `search_query` has many `users` as results.
- `search_query` has many `users` as search requesters (the people who initiate the search)

Search requesters can be nil if the search was done by a not logged in user of the page.
## Misc

In the first step a user can only search for email addresses. In the future we'll add a search by last_name and first_name feature to this model. Please feel free to create better field names.

Please contact me in case something is missing or not clear.

**Comment by cjfreeze** [comment]
Are we wanting to store these querys? Is this for a search history feature?

**Comment by wintermeyer** [comment]
Yes, we want to store them. This opens a door for future optimizations and we have a history.

**Comment by cjfreeze** [comment]
Say two users at different times search identical queries, would we want two different db entries or would we detect the existing query and add the later user to requesters?

**Comment by cjfreeze** [comment]
Got it.

**Comment by cjfreeze** [comment]
What about timestamps per requester? We might want to do a join table for timestamps, so each query can have many "searches" which consist of a user_id and a timestamp.

**Comment by wintermeyer** [comment]
When I talk about a model I always think full model. So we have inserted_at to store that information.

**Comment by wintermeyer** [comment]
In the join model that is.

**Comment by cjfreeze** [comment]
Results will change over time, and it will be difficult to sort them if they all belong to the query, so it makes sense to have them belong to the request. The tree will then be 
`Search Query->Search Request->Search Results`
`Search Query: value, is_email?`
`Search Request: user_id, query_id`
`Search Result: request_id, user_id`
