### ISSUE TITLE
Create a search_term resource

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#150]
# Idea

One DB table with all possible search terms for a given `user`. It will not be possible to cover 100% but 80% are better than nothing.
# Model

The model `search_terms` has the following fields:
- `value` : string
- `closeness` : integer
- `user_id` : integer

`closeness` will be 100 for email addresses and other information where we know 
that it is very precise. Think of it in percent.
## Index

There has to be an index on `value`.
## Associations

A `user` has many `search_terms` and the `search_term` belongs to a `user.
## Validations
- `value` can't be nil or blank
- `user_id` must be an integer
- `user` must exist
# Nesting

The resource is nested under `/users/:slug/search_terms/`. Only the `search_terms` for a given user are displayed. Only the user and admins can read/write this resource.

**Comment by cjfreeze** [comment]
Ah, so you're planning to let the user set their `search_terms`. Should we have specific terms that aren't editable? I was planning on creating a function that generates `search_terms`, that would be called when a user changes a value, such as `last_name`, and when the user is created. It would apply common mutations to their email and names (c to k, etc) to improve search coverage. We could also choose whether to display these system-generated terms to the user.

**Comment by wintermeyer** [comment]
Yes, the user can set his/her own search_terms. But that is just an option. The system should do good enough defaults.

About the mutations: I'm going to create a separate issue for that.

**Comment by wintermeyer** [comment]
See https://github.com/vutuv/vutuv/issues/154 and https://github.com/vutuv/vutuv/issues/155 for the mutations.
