### ISSUE TITLE
Add cologne phonetics for last_name, first_name and combinations to search_terms

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#154]
Please create cologne phonetics `search_terms` for the same combinations as in https://github.com/vutuv/vutuv/issues/153

https://en.wikipedia.org/wiki/Cologne_phonetics describes how cologne phonetics work.

**Comment by cjfreeze** [comment]
So to confirm, you want to reduce names to phonetic codes? For example, Chris would encode to 478. Kris would also encode to 478. meaning the words sound similar enough to match. And you want to add these codes as search terms?

**Comment by wintermeyer** [comment]
Yes, I want those `search_terms` to be added to the already existing ones. But with a lower score (e.g. 80).

**Comment by cjfreeze** [comment]
I found an elixir library that supports the Metaphone Algorithm. Would you like to try that, or would you like me to go ahead and implement the cologne and soundex algorithms?

**Comment by wintermeyer** [comment]
Are you talking about https://github.com/smashedtoatoms/the_fuzz? That one you can use for https://github.com/vutuv/vutuv/issues/155 but not for https://github.com/vutuv/vutuv/issues/154. For https://github.com/vutuv/vutuv/issues/154 you need to use cologne phonetics or something else which takes care of the German language rules.

**Comment by cjfreeze** [comment]
Got it. I'll probably just implement both then.
