### ISSUE TITLE
Add cologne phonetics and soundex to search_queries

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#156]
If the `value` of a `search_query` is not an e-mail address than downcase it and search for it in the `search_queries`. If that doesn't deliver a result do the same with cologne phonetics and soundex versions of `value`.

**Comment by cjfreeze** [comment]
So we only want to try the phonetics if we get no results without? Checking both simultaneously is one less database call.

**Comment by wintermeyer** [comment]
Obviously one search is better than too. So why not do one search for all and take the 100 result for the email if it exists?

**Comment by cjfreeze** [comment]
Currently the code only searches for `search_terms` if it doesn't detect the `search value` to be an `email`. If it does it just gets all `users` by `email`. Thinking about it now, at that point we could just redirect. If it doesn't detect an `email` it tries to match `search_terms` with and without phoneticizing the `search value`, and does so in a single database call. Is there anything you would change about this method?
