### ISSUE TITLE
Use gravatar as a backup if no avatar was uploaded

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#159]
In case the user hasn't uploaded an avatar use the one from http://www.gravatar.com

![bildschirmfoto 2016-09-17 um 08 11 42](https://cloud.githubusercontent.com/assets/69770/18606375/a0377bc6-7cae-11e6-9173-81d364d0602f.png)

**Comment by cjfreeze** [comment]
While I'd like to have avatars imported from facebook if facebook login is used to create account, or taken from gravatar if an email is given, and have these avatars stored in the system, for now I'm just re-adding the old gravatar line of code.
