### ISSUE TITLE
Securely store API keys

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#162]
Because this is an open source project, it's pretty dangerous to have API keys stored anywhere visible to others. That even includes the /config scripts. We need to find a solution to this. Services like Heroku offer storing values which are then passed to your application when launched, but I'm not sure what we are using for a webserver. For now they're stored inline in the code, which means to be safe we'll need to generate new keys when we go live/implement them securely.

**Comment by wintermeyer** [comment]
I agree and upgrade this to be a bug.

**Comment by wintermeyer** [comment]
I'm not 100% sure but I think solving this with environment variables is the best way to go (`Application.get_env/3`). But I'm open for other solutions. Anyhow we have to document the use of the solution in the `README.md` file.

**Comment by cjfreeze** [comment]
If we're not using anything provided by a hosting service, the go-to solution is `prod.secret.exs`

We should add an example of this file's contents to the readme (without the keys of course). We'll need to create identical files on all developer computers that want to use facebook's api in development, and when the site goes live, it will need the file created for it as well.
