### ISSUE TITLE
`search_terms` don't update after users#edit and users#update

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#167]
When I change the values of a `user` (e.g. `first_name`) the old `search_terms` should automatically be deleted and new ones generated. Or the old ones should be updated. I guess deleting and generating is easier.

**Comment by cjfreeze** [comment]
As it would happen, updating is much easier than deleting and generating, with the unfortunate consequence of deleting all of the user's search_terms during the update, including user created terms.
