### ISSUE TITLE
Test for creating a new user

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#169]
I don't know how much work this is but I'd like to have one automated test which starts the application and creates a new user on the index page and checks the result on `users#show`. That's the most important test.

**Comment by cjfreeze** [comment]
Just one test isn't hard at all, it's all very streamlined. As a whole, writing tests for everything is a very menial task though. I'd rate this individual issue a 2/10 for scale, but tests for everything a 8/10

**Comment by cjfreeze** [comment]
This test ended up being a bit more complicated as I had not taken into account the magic link exchange which takes place in the middle of this process. I've decided to just do a suite of tests for user that covers several different cases.
