### ISSUE TITLE
Magic link has to be sent after users#create

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#170]
The application has one serious problem: Anyone could create accounts for other persons without them knowing. That could be harmful if they publish wrong information for that account. 

Therefor we have to add one step in the registration process. The `users#create` function can not login a new user automatically but has to send him/her a magic link. If possible this should be as DRY as possible by using the same functions we already provide for the login. A new user should get a magic link by email and a message which says "Thank you for registering on vutuv. To confirm your email address we just sent you an email with a login link. Please check your inbox. And don't forget your spam folder in case you don't receive an email within 3 minutes."

**Comment by cjfreeze** [comment]
The magic link system was designed to be used with a smtp server. We even have a library and email templates set up, all we need is an smtp server.

**Comment by wintermeyer** [comment]
The SMTP server will be there. No problem.

**Comment by cjfreeze** [comment]
If I disable the flash system, we won't be able to create new accounts without the smtp server though. I guess we can still login via facebook.

**Comment by wintermeyer** [comment]
No reason not to have the flash system for development. Please describe the problem.

**Comment by cjfreeze** [comment]
Nevermind me, I just misunderstood. No problems. Though to minimize potential bugs let me know what SMTP server software you are planning to use so I can use it for development.

**Comment by wintermeyer** [comment]
Postfix. But I trust in the library you used. SMTP is a standard.
