### ISSUE TITLE
Email verification for new entries

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#171]
To cover the problem described in https://github.com/vutuv/vutuv/issues/170 we have to verify each new email address. ~~I guess we'd have to add a `verified` boolean to the email model and set it `false` until it has been verified by a magic link.~~ When adding an email address to a user, a magic link is required to add the email. No changes to the model are made until the user verifies the email via magic link. This will be required for every email creation.

~~The user has to be auto logged out after creating a new email. Then a magic link has to be sent to him/her and a message has to inform him/her what to do.~~ Because the magic link is creating the email, it does not matter if the user is logged in or not. The magic link will also not log the user in. 

~~PS: Please don't forget the right handling of `search_terms`. A new email address can not be a `search_term` until it has been validated.~~ Since all emails are `search_terms` without having to be added as a `search_term` no action is needed in this category.

**Comment by cjfreeze** [comment]
We already have a verified boolean for user, but it has it's own uses, so adding a verified field to email while leaving the user verified field alone is appropriate. 

I don't see why a user needs to be logged out for email verification though, it's just going to be a different magic link route.

**Comment by wintermeyer** [comment]
The user has to be logged out first because otherwise one could create an account for a third person.
