### ISSUE TITLE
No cookies when a user doesn't send cookies

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#174]
If a user of the page without an account visit the page he/she should not receive a cookie.

**Comment by cjfreeze** [comment]
I can prevent the cookie, but it's required to do anything in the site. Submitting any form without it will result in an `invalid CSRF token` error. I could prevent it on the home page, but if I did that you wouldn't even be able to submit the registration form that's embedded in the home page.

**Comment by wintermeyer** [comment]
Could you do me a favor and check with a http://stackoverflow.com/ question or on the IRC if it is really not possible to do this? In Rails you can say the framework that it should go easy on the CSRF token for special controllers or actions.

**Comment by cjfreeze** [comment]
You choose which routes aren't checked for forgery by changing where the plug `protect_from_forgery` is called. I could try and design my plug to also plug the crsf check only when it's allowing a cookie...
