### ISSUE TITLE
Email doesn't need to be a search term

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#176]
Because of the way we designed `search_query`, if `email` isn't added to `search_terms` it will still be searched for when `search_query.is_email?` is set to true, which happens whenever the `search_query` is determined to be an email via validation. Even if we did store `email` as a `search_term`, the term would effectively never be used.

**Comment by wintermeyer** [comment]
The idea of having the email address as a `search_term` too is mainly searching performance improvement. Plus it would be nice to have soundex and cologne phonetics for emails too. But we don't need it right now and can tackle it in the future in case we'll need it. Your call.

**Comment by cjfreeze** [comment]
As far as performance goes, if the search query matches the email regex then it literally gets the user by email, and ignores search terms altogether, so performance is unchanged by if email is a search term. The phonetics for search terms is a good point though. I am unsure what the best way to implement it would be, and it would be something we should implement in the future. I'll create an issue for that and set its milestone to 1.1
