### ISSUE TITLE
Builds not passing due to no SMTP server in TravisCI

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#178]
We either need to somehow provide a test smtp server in TravisCI or figure out a way to ignore if a server does not exist when testing emails.

**Comment by wintermeyer** [comment]
To install an SMTP server in Travis CI is no problem. Please have a look at http://michaelthessel.com/mock-mail-setup-for-travis-ci/ for this example:

```
[...]
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
[...]
```
