### ISSUE TITLE
Remove Facebook auth functionality to a Pull-Request

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#179]
I'd feel better to start with a vanilla login version of the application and to have the Facebook auth functionality on stand by in a separate Pull-Request. Please move all code and the migrations to a new Pull-Request.

Sorry for the work this involves. I just feel better to keep it simple in the beginning.

**Comment by cjfreeze** [comment]
I'm going to leave some of the code that was written for the facebook auth system because it was also written for other uses as well, namely the `oauth_provider` model. That being said, I realized that `oauth_provider` as a model doesn't need a controller so I am removing that.

**Comment by cjfreeze** [comment]
Closed by https://github.com/vutuv/vutuv/pull/180
