### ISSUE TITLE
Round avatar with css

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#204]
Avatars are currently displayed as a square, they should be displayed as a circle.

**Comment by cfroerup** [comment]
We could do that however Opera Mini disables border radius so maybe it would be better to round the images on the server

**Comment by wintermeyer** [comment]
Thanks for the input about the Opera Mini. I didn't know that. We will round the images on the server. But please do the CSS anyway because I expect JPEG compression issues. Quality wise. So I'd like to do both and have a very good result on most and an 80% good result on Opera Mini.
