### ISSUE TITLE
Follow links in break due to generated form tag

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#205]
In the user's profile page:
Follow buttons are misbehaving.
![Image](https://files.slack.com/files-pri/T143NTF7E-F2VUX2KCM/followlinks.png?pub_secret=044d992275)

The reason is as follows:

**In provided html**
```
<p><strong>Name</strong>
Jobtitle @ Organization</p>
<a href="#" class="button button--icon">
	<i class="icon icon--unfollow"></i>
</a>
```
**In actual html**
```
<p><strong>Name</strong>
Jobtitle @ Organization</p>
<form action="/connections/1" class="link" method="post">
	<input name="_method" type="hidden" value="delete">
	<input name="_csrf_token" type="hidden" value="">
	<a class="button button--icon" data-submit="parent" href="#" rel="nofollow">
    	<i class="icon icon--unfollow"></i>
	</a>
</form>
```
Phoenix creates the links inside forms. The CSS most likely does not handle this correctly.

**Comment by cfroerup** [comment]
Can you me the final html generated from the system?

And please add class button-list__button to the form the I'll add the styling

**Comment by cjfreeze** [comment]
Here is the html excerpt, the class has been updated. I am also gisting the entire html, but fair warning the formatting is going to be bad.
[gist](https://gist.github.com/cjfreeze/530ca4ee88f7e2fa1212b35a616f3c93)

```
<section class="card half">
  <h1>Followers</h1>
  <ul class="button-list profiles">
    <li>
      <div><img src="data:image/jpg;base64,<stripped for size>"></div>
      <p><strong>Chris Freeze</strong></p>

      <!-- here is the form in question -->

      <form action="/connections/3" class="button-list__button" method="post">

        <input name="_method" type="hidden" value="delete">

        <input name="_csrf_token" type="hidden" value="bVVxIDItIQF0GgAwMGJqGBk5PAo8EAAA41EmUHwDDq9yv48mUthnzg==">

        <a class="button button--icon" data-submit="parent" href="#" rel="nofollow">
          <i class="icon icon--unfollow">
        </a>

      </form>
    </li>
  </ul>
</section>
```

**Comment by cjfreeze** [comment]
I inspected the elements with firefox and saw some very strange behavior going on. The `<i>` element is duplicated 4 times. Note that this is not reflected in the page source, which has not changed. Removing the `<form>` fixes the css bug but breaks the link, as a link cannot `POST` without a `<form>`. I wonder what about the `<form>` causes the `<icon>` to duplicate itself.
![strange behavior](https://cloud.githubusercontent.com/assets/11078691/20004046/f05862f4-a257-11e6-97fe-a2937537d576.png)

**Comment by cjfreeze** [comment]
We're going to postpone this issue to milestone 1.1
Until then, we will not have follow links in attached to the user's profile cards.

**Comment by cjfreeze** [comment]
I found the source of this bug. I mistakenly did not close an `<i>` element. Turns out forms had nothing to do with it.
