### ISSUE TITLE
Strange background image behavior on homepage

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#206]
The background on the homepage only repeats for a certain distance underneath the imagebox card. I don't see this behavior on the example [here](http://vutuv.dev.freyventures.com/app/)
What could be causing this?
![image](https://files.slack.com/files-pri/T143NTF7E-F2WDM4NQ5/pasted_image_at_2016_10_31_12_43_pm.png?pub_secret=7dcc941efd)

Here is an animated example to more accurately illustrate the issue. In the example I am zooming in and out of the page.

![ezgif-508287491](https://cloud.githubusercontent.com/assets/11078691/19903976/a9e699f0-a03e-11e6-9aea-5997bace74fb.gif)

**Comment by cfroerup** [comment]
What browser is this?

**Comment by cjfreeze** [comment]
Waterfox, A 64 bit version of firefox. I have reproduced the issue in chrome though.

![chrome](https://cloud.githubusercontent.com/assets/11078691/19929437/c256d7a2-a0d9-11e6-991f-93e2dabac1ef.png)

[Here is a gist](https://gist.github.com/cjfreeze/07d169c3b4758fedd94933fe1c3e131d) of the html for index.

**Comment by cfroerup** [comment]
I havent been able to reproduce this bug in chrome, what version of chrome is used? @cjfreeze

**Comment by cjfreeze** [comment]
I have absolutely no idea what caused this bug... but in an attempt to determine this bug's origin, I somehow inadvertently fixed it. The homepage now behaves correctly, and I have no idea what changed to make this happen.

Oh well.
