### ISSUE TITLE
Labels for nav icons

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#207]
We would like css for text instead of icons in the nav.

**Comment by wintermeyer** [comment]
I liked Kasper's take on this problem:
![bildschirmfoto 2016-11-01 um 17 59 33](https://cloud.githubusercontent.com/assets/69770/19898853/123c68da-a05e-11e6-86e7-d1f77534eaa9.png)

I'd like to have a breadcrumb style text only navigation on the left side of the navigation bar.

**Important:** I'm not saying that we have to put the breadcrumbs on the left top side of the navigation bar. In case we are running into real estate problems on mobile phones we can put it somewhere else. But we should get rid of the back-button functionality. That is a functionality already solved by the browser.
