### ISSUE TITLE
CSS for Work Experience cards

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#211]
This card will contain the job title, the organization/company the job was with, a description of the job, and the start/end year/month. End dates are optional, as users can include current employment. Months are also optional. The minimum information required for a work experience is a title and organization.

Example picture of crude implementation
![Image](https://files.slack.com/files-pri/T143NTF7E-F2WS43LR1/pasted_image_at_2016_11_01_09_51_am.png?pub_secret=d979f5387f)

**Comment by cfroerup** [comment]
There is work experience cards. They are on profile-edit.php, there is not a description on yet.

**Comment by cfroerup** [comment]
Can we see a worst case scenario data-wise. For example an address to be shown in a card.

**Comment by cjfreeze** [comment]
For work experience, the only fields will be job title, description, Organization, and start-date/end-date
if the existing cards support these, then consider this one my bad and close the issue :)
