### ISSUE TITLE
CSS for phone numbers

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#212]
Very simple, might not even need additional CSS, but I do want a way that looks better than what I currently have. The model has 2 fields, the number and the number type.

![image](https://files.slack.com/files-pri/T143NTF7E-F2WTTN9C5/pasted_image_at_2016_11_01_09_50_am.png?pub_secret=3c7db0b86d)

**Comment by cfroerup** [comment]
We some need more info on this one. What should we change?

**Comment by cjfreeze** [comment]
The idea is I'm just looking for a more aesthetically pleasing way of displaying data pairs. I'm not very gifted in this category, so I'm looking for input from you and your team. This goes for links as well.
