### ISSUE TITLE
CSS for links

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#213]
Like phone numbers, very simple but could use improvement. Two fields: The link and a link description, provided by the user, but with a limited length. The link will be in an `<a>` tag.

![image](https://files.slack.com/files-pri/T143NTF7E-F2WS3PK7V/pasted_image_at_2016_11_01_09_50_am.png?pub_secret=e84081859a)

**Comment by cfroerup** [comment]
We need more info on this. What should we change?

**Comment by cjfreeze** [comment]
The idea is I'm just looking for a more aesthetically pleasing way of displaying data pairs. I'm not very gifted in this category, so I'm looking for input from you and your team. This goes for phone numbers as well. Specifically for links, there could be some CSS changing how they behave visually if you think it could improve the aesthetics of the page.

**Comment by wintermeyer** [comment]
I understand both sides. I talked to @cjfreeze about this. We are going to go forward and just implement the default scaffolding HTML to show @cfroerup what data is going to be displayed. That should narrow down the problem. I close this issue for now.
