### ISSUE TITLE
CSS for listing addresses

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#214]
Easily the most complicated card, addresses need to be displayed with correct formatting that makes sense to the user. There are an unfortunately large amount of ways to display addresses from different countries, but we luckily only have to worry about Germany and the US for now. As for fields, addresses have the following to cover all international addresses:
![image](https://files.slack.com/files-pri/T143NTF7E-F2WTY01KR/pasted_image_at_2016_11_01_09_50_am.png?pub_secret=3dbfda452b)
However not all countries use these fields, and many of them use these fields differently. For our two cases, Germany and the US, they are formatted as follows:
German addresses:

US addresses:
```
Line 1:     <street number><street name><street type>   e.g. 1234 Washington Street
Line 2:     <PO box/APT> <number>                       e.g. Apartment 305
City:       Self explanatory                            e.g. Austin
State:      Self explanatory                            e.g. TX (always abbreviated)
Zip code:   A 5 digit number for post offices           e.g. 78732
```
US addresses do not use lines 3 and 4
However US residents combine the 3 final fields on the same line when writing their address, meaning a correctly formatted US address would look like this:
```
1234 Washington Street
Apartment 305
Austin, TX 78732
United States
```
The second line is optional, and is often not used. An address without line 2 looks the same as above, but without the second line.
All addresses have their country last.

**Comment by wintermeyer** [comment]
I like the way Twitter Bootstrap solves this problem. http://getbootstrap.com/css/

![bildschirmfoto 2016-11-01 um 17 16 51](https://cloud.githubusercontent.com/assets/69770/19897095/0ce2d736-a057-11e6-83ac-b6588e9960ff.png)

**Comment by cjfreeze** [comment]
I'll try to implement it without additional CSS, and if I have trouble I'll reopen the issue with new information.
