### ISSUE TITLE
Missing gender select in the users#new form

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#217]
In `page#index` the form to create a new user is missing the `gender` drop down with the entries male, female, other.

![bildschirmfoto 2016-11-02 um 07 44 42](https://cloud.githubusercontent.com/assets/69770/19919010/4df713d0-a0d0-11e6-94fb-75f07db55c97.png)

**Comment by cjfreeze** [comment]
It seems there is a lack of styles for the select, here is a screenshot.

![form](https://cloud.githubusercontent.com/assets/11078691/19930665/d5ede55c-a0df-11e6-8c0c-cb6a467f1d59.png)

Assigning this to @cfroerup for the finishing touches.
