### ISSUE TITLE
Neither display empty gender nor birthday

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#220]
If there is no gender or birthday it shouldn't be displayed at all.

![bildschirmfoto 2016-11-02 um 13 52 26](https://cloud.githubusercontent.com/assets/69770/19929448/b940cc98-a103-11e6-835e-6be3133afdd8.png)

**Comment by cjfreeze** [comment]
I am also going to hide gender if other is selected. Let me know if you want other to be displayed.
