### ISSUE TITLE
Validation error for phone_numbers

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#221]
When I try to create a new phone_number I get a validation error for a good phone number:

![bildschirmfoto 2016-11-02 um 13 58 33](https://cloud.githubusercontent.com/assets/69770/19929680/d145e4da-a104-11e6-96af-6573ca7e9eae.png)

Actually this format "+49 1234 121241" is kind of the best case scenario. Because we can scan the country code and the area code from it.

**Comment by cjfreeze** [comment]
Ah, it's the plus and the spaces. Consider this a subissue of #183 .
