### ISSUE TITLE
Css for resource display tables

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#222]
An easy way to do resource displays would be a simple table in a card. I tried to write a table and it ended up looking like this:

![table](https://cloud.githubusercontent.com/assets/11078691/19930332/5d63f78a-a0de-11e6-9f99-de8596f60121.png)

So it seems all it needs is some styles, and it would be fine. Have it fill the space, add some icons for the links to make them buttons, and whatever else makes it look nice.

**Comment by cjfreeze** [comment]
What are your thoughts on this, particularly as it relates to issue #216?

**Comment by wintermeyer** [comment]
For now something like Twitter Bootstrap striped would work.

![bildschirmfoto 2016-11-02 um 14 31 01](https://cloud.githubusercontent.com/assets/69770/19930503/0b51884c-a109-11e6-8f36-507f0a5ecb21.png)

In addition we would need some sort of buttons to link the show, edit and delete actions.

![bildschirmfoto 2016-11-02 um 14 31 58](https://cloud.githubusercontent.com/assets/69770/19930533/2bd90da6-a109-11e6-82b8-f20ce4a62044.png)

**Comment by wintermeyer** [comment]
The Phoenix default looks like this:

![bildschirmfoto 2016-11-02 um 14 32 58](https://cloud.githubusercontent.com/assets/69770/19930566/4dc4f74a-a109-11e6-8f6b-2ee7d34c78d1.png)

We need the same functionality. Just nicer design. But for now functionality is more important than design.

**Comment by cfroerup** [comment]
We will style the table
