### ISSUE TITLE
Let create of user_controller render new_registration without a redirect

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#223]
Currently `user_controller.ex` triggers this redirect:

    |> redirect(to: page_path(conn, :new_registration))

But that adds an other TCP roundtrip because that redirect is triggered by the browser. So more work for the browser and the server.

Please restructure to logic/code so that the form in `page#index` calls `page#new_registration` and put the user create code there. In case there is a code duplication with `users#create` than open an issue for 1.1 - we can deal with that later. 

Please contact @wintermeyer in case something is unclear.

**Comment by cjfreeze** [comment]
This was mistakenly not closed. It has been fixed.
