### ISSUE TITLE
Create an easy form to create skills for new users

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#224]
I'd like to lead a new user to create skills right after he/she logged in the first time. To achieve that it has to be super simple. Please add a form in the skill card:

![bildschirmfoto 2016-11-03 um 07 52 07](https://cloud.githubusercontent.com/assets/69770/19957844/7391190e-a19a-11e6-9f2a-8b33f4689b6a.png)

The form has one text field with the text "Enter your skills. e.g. JavaScript, Kung Fu, Origami". That form triggers a comma separated split of this text field and creates those skills for the user. After that it will redirect to `users#show`.

I don't like the redirect because it is a waste of resources but I don't see a cleaner way. But please do it differently if you have a better idea.

**Comment by cjfreeze** [comment]
We can use channels to have the field live update
