### ISSUE TITLE
Crop an avatar into a circle

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#230]
We need to store the avatars as circles because of Opera Mini (https://github.com/vutuv/vutuv/issues/204). This can be done with ImageMagick and as far as I understand arc this is a piece of cake.

On http://stackoverflow.com/questions/999251/crop-or-mask-an-image-into-a-circle there is this code example:

    convert -size 200x200 xc:none -fill walter.jpg -draw "circle 100,100 100,1" circle_thumb.png

Please contact @wintermeyer if you run into any ImageMagick problems.

And please be sure that we store the original image always without any changes. In case we are going to change the design in the future.

**Comment by wintermeyer** [comment]
I'm postponing this feature for now. I'd like to put some more work into impact of this to the file size of the jpg. A quick test on https://tinypng.com was disappointing but I didn't spend much time with this. Opera Mini users will excuse this minor issue.

**Comment by cjfreeze** [comment]
Arc ecto makes this way harder than it needs to be anyway. Any type of drawing requires the image type to be known by imagemagick, and arc-ecto delivers the images without an extension to the transform functions, causing unexpected behavior. Off the top of my head it seems like the only fix would be to temporarily rename the file with it's proper extension, then rename it back so arc-ecto can delete it properly. And that is just terrible.
