### ISSUE TITLE
Form fields

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#233]
Today I tested the initial user create form on different platforms. It works good on classic desktop browsers:

![bildschirmfoto 2016-11-03 um 16 06 12](https://cloud.githubusercontent.com/assets/69770/19971691/0f4ba1e4-a1e0-11e6-992a-819a5308a593.png)

But on some mobile browsers it is not easy to see what in a given field has to be entered:

![bildschirmfoto 2016-11-03 um 16 07 01](https://cloud.githubusercontent.com/assets/69770/19971701/17b3976a-a1e0-11e6-91bc-b6470f934f21.png)

And for accessibility it is a night mare:

![bildschirmfoto 2016-11-03 um 16 06 23](https://cloud.githubusercontent.com/assets/69770/19971710/1f650872-a1e0-11e6-96f7-fb93271ea0e4.png)

Can we put the requested field type (e.g. First name) on top of the input field? It might not be as pretty but many users will be thankful for it.

**Comment by wintermeyer** [comment]
https://developers.google.com/web/fundamentals/accessibility/

**Comment by cfroerup** [comment]
Thanks, we will look into this.
