### ISSUE TITLE
Add a slack to the User model

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#24]
We don't want `user#show` available at `/users/1` or `/users/2` but at some sort of readable slug (e.g. `/users/stefan-wintermeyer`. Obviously there is the chance of more than one `stefan-wintermeyer` in the system. So we have to add a counter or a random value behind it. Or make it available for the user to change. Have a look at https://github.com/norman/friendly_id

A `User` should `has_many` `slugs`. So a user can create a new slug without destroying the old one.

Old `slugs` don't get deleted.

**Comment by wintermeyer** [comment]
http://www.phoenixframework.org/docs/ecto-custom-primary-keys
https://blog.fourk.io/uuids-as-primary-keys-in-phoenix-with-ecto-and-elixir-1dd79e1ecc2e#.74i4bnr1e

**Comment by cjfreeze** [comment]
There are two options with slugs. Option A is to have them be a simple redirect, and the id is still used for all other routing. Option B is to replace id entirely in the URL. It would be possible, but impractical to do some combination of the two options. Which option do you prefer?

**Comment by wintermeyer** [comment]
The best way would be to have one slug which is the main one. All others should be redirected (with a correct 302 HTTP redirect) to the main one.

Thought: It could become handy to have a `disable` functionality for some slugs. Those should answer with a 404 HTTP. I'm sure some users will come up with slugs that are offending. For that a `disable` functionality would be handy.
