### ISSUE TITLE
Add Edit and Delete buttons to every card

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#242]
Similarly to the edit buttons, we need delete buttons for each card. Here is an example.

![delete2](https://cloud.githubusercontent.com/assets/11078691/20205106/a88d1728-a79b-11e6-90ce-ce8cf76499e6.png)

The thing is, we want the option to have edit/delete buttons for every single item in every single card. I've attempted to throw something together, but I have to say it doesn't look very good. For example, with skills:

![skilldelete](https://cloud.githubusercontent.com/assets/11078691/20205135/f195d086-a79b-11e6-8de4-ddc2dbf03a7f.png)

And with some other generic resources

![phonebuttons](https://cloud.githubusercontent.com/assets/11078691/20205158/2176a1d6-a79c-11e6-846d-f7936c9aaa47.png)

The main requirement is that it all needs to be uniform. I want the user to be able to instantly know where these buttons are going to be in a card regardless of the type of card. I think that your buttons in the work experience card are excellent and think that you should try and model the other cards off of it.

**Comment by cfroerup** [comment]
Would we not rather want these as a button on the edit page? Anyhow, we will create a delete icon.
