### ISSUE TITLE
Add a delete button icon

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#243]
As seen in #242, I have added a temporary delete button icon. 

![deleteicon](https://cloud.githubusercontent.com/assets/11078691/20205427/4b0e66b2-a79e-11e6-917d-95de7fba9430.png)

However it would be much better if you provided one. It would most likely fit better with the other icons and we won't have to worry about any legal issues (I just found this online after all)

**Comment by wintermeyer** [comment]
Just a reminder for everybody: This project is MIT licensed. All images used have to be too.

**Comment by cfroerup** [comment]
Would we not rather want these as a button on the edit page? Anyhow, we will create a delete icon.
