### ISSUE TITLE
Bug in phone number validation

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#271]
The phone number validation doesn't accept good numbers:

![bildschirmfoto 2016-11-14 um 14 45 58](https://cloud.githubusercontent.com/assets/69770/20267051/38983048-aa79-11e6-900d-afccaff49e94.png)

![bildschirmfoto 2016-11-14 um 14 46 09](https://cloud.githubusercontent.com/assets/69770/20267053/3a62a08e-aa79-11e6-9396-fb81d721bfcb.png)

![bildschirmfoto 2016-11-14 um 14 46 19](https://cloud.githubusercontent.com/assets/69770/20267056/3c2a7266-aa79-11e6-8b9f-f4751a77da11.png)

**Comment by cjfreeze** [comment]
I was able to successfully add all three of those phone numbers. I'm thinking this might have something to do with whitespace. 

![whitespace validation error phone number](https://cloud.githubusercontent.com/assets/11078691/20306135/74322552-aafe-11e6-813c-ecb10b75d46c.png)

I've fixed this issue, so please test these numbers with the new code to confirm.
