### ISSUE TITLE
Personalised greeting in the magic link email

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#276]
The greeting in `web/templates/email/login_email.text.eex` should be personalised. It should say "Hello Mr. Wintermeyer," or "Hello Stefan,". 

And the `gen_email(link, email, template)` function in `lib/vutuv/emailer.ex` should use the first_name and last_name for the `TO:` field of the email too. Currently the email is send to "stefan.wintermeyer@amooma.de`. But it should be send to `Stefan Wintermeyer <stefan.wintermeyer@amooma.de>`. The `|> to(email)` has to be changed.

**Comment by cjfreeze** [comment]
I'm going to sleep on this one, I've got a few different ideas for the emails.

**Comment by wintermeyer** [comment]
I'm going to split this issue into sub issues. Some stuff in it is not as important than other.
