### ISSUE TITLE
HTML error in the social_media_accounts form

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#284]
During a validation error there is a HTML error on top of the form:

![bildschirmfoto 2016-11-17 um 08 01 04](https://cloud.githubusercontent.com/assets/69770/20379351/1dcb6562-ac9c-11e6-8c60-276e47b5298a.png)

**Comment by cjfreeze** [comment]
This was closed in 115b84eb659c8659aa36c018d275f8b0e9ac55ae but I mistakenly forgot to mention it and close it via commit.
