### ISSUE TITLE
Unfollow button should be grey but not blue

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#311]
I find it confusing that the unfollow and the follow button use the same colours. Blue should be positive and unfollow is not positive.

Not the right color:
![bildschirmfoto 2016-11-19 um 14 41 03](https://cloud.githubusercontent.com/assets/69770/20455871/9f00f2d4-ae66-11e6-8d81-411e8da95133.png)

Better would be:
![bildschirmfoto 2016-11-19 um 14 43 44](https://cloud.githubusercontent.com/assets/69770/20455873/a409e5ec-ae66-11e6-9970-14dc26766bea.png)

**Comment by cjfreeze** [comment]
This was closed in 0f4c63441db288a5487be01c417b0a0363fa34bd
