### ISSUE TITLE
Wrong image in users#edit

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#318]
There is a misplaced icon in users#edit. It shouldn't be there at all or should it?

![screenshot at nov 19 17-19-22](https://cloud.githubusercontent.com/assets/69770/20456735/958502b6-ae7c-11e6-89f3-c1beecb1112a.png)

**Comment by cjfreeze** [comment]
As of 2ca8b1a640e0768af0c35bd1e0fc29cec54b292c, it is no longer there. It used to be the delete link for the user though.
