### ISSUE TITLE
Don't display the link to user#show if it's that current page.

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#32]
If the user with the id 1 visits `/users/1` he/she shouldn't see a self referring link in the top navigation bar. Just his/her full_name(@current_user).
http://stackoverflow.com/questions/37029040/no-link-if-current-page

![bildschirmfoto 2016-05-04 um 15 31 27](https://cloud.githubusercontent.com/assets/69770/15015671/911c571c-120d-11e6-863e-9d7323727119.png)

**Comment by wintermeyer** [comment]
http://stackoverflow.com/questions/31572653/apply-css-class-on-element-if-current-page-in-phoenix

**Comment by cjfreeze** [comment]
I feel the function is_current_user_page?/1 has a somewhat unclear name but I was drawing a blank when naming it, so if anyone wants to suggest a better name please do so.

The function simply returns true if the current user is viewing their own user page.
