### ISSUE TITLE
A login with a non existing email address needs to be handled

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#33]
When using an not existing email address you get the following error:

![bildschirmfoto 2016-06-24 um 07 17 20](https://cloud.githubusercontent.com/assets/69770/16328557/bb5ea4da-39db-11e6-91b5-adeb62aa69c5.png)

What we want it to redirect the user the either the login screen or the root path and give him/her a proper error message.

I'm aware of the possible "by that way one can check if someone has an account" problem. We might have to not give the user an error message.

**Comment by cjfreeze** [comment]
When you have a password field, that will solve the checking if a user has an account problem because the snooper won't be able to tell if the error message was generated by an incorrect password or a nonexistent email.
