### ISSUE TITLE
Sorting of work experiences is wrong

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#333]
On users#show the work experiences should be sorted vice the versa. The current position should be on top.

![bildschirmfoto 2016-11-20 um 18 49 55](https://cloud.githubusercontent.com/assets/69770/20464921/41b7a4be-af52-11e6-8133-d2ca3d51f0b3.png)

**Comment by cjfreeze** [comment]
This was fixed in 51dd0aabefa280313c9330db76bf195531f79919
