### ISSUE TITLE
(vutuv.de/{user}/edit link produces Errorcode 500 (server internal error)

### ISSUE THREAD

**Issue by DerLordi** [wintermeyer/vutuv#351]
When typing manually the edit link (vutuv.de/{user}/edit) when not logged in, the server should not produce the errorcode 500. A 404 error site should be better.

![bildschirmfoto 2016-11-22 um 13 48 54](https://cloud.githubusercontent.com/assets/4737847/20524423/d02488de-b0ba-11e6-8407-cb23d755ab4a.png)

**Comment by wintermeyer** [comment]
@DerLordi is right.

**Comment by cjfreeze** [comment]
Wouldn't it be 403? The error page is shown due to trying to edit another user when they aren't authorized.

**Comment by wintermeyer** [comment]
You're right! 403 is better.

**Comment by cjfreeze** [comment]
Looks like we're good on this issue then. It currently displays 403.
