### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#352]
Hi together,

first, nice web application! :)

So the issue:
Different links show up "page not found" like when I want to edit my skills or email address. Same happens when I want to look skills from other users.

Regards
Gino

**Comment by wintermeyer** [comment]
First: Thank you! :-)

Can you attach screenshots and add the URLs?

**Comment by ThraaxSession** [comment]
1. Link: [https://www.vutuv.de/users/gino.atlas/emails](https://www.vutuv.de/users/gino.atlas/emails)
2. Screenshot to link.
![vutuv](https://cloud.githubusercontent.com/assets/3085830/20524664/ce32ed3a-b0bb-11e6-81a4-71caac97ede1.png)

Update: That's from another user either: [https://www.vutuv.de/users/thomas.grosse1/skills](https://www.vutuv.de/users/thomas.grosse1/skills)

**Comment by cjfreeze** [comment]
@GinoHereIam Could you try to re-login for me?

**Comment by cjfreeze** [comment]
Closed by 72254b2cd141891573086004d258694551d6db6d
