### ISSUE TITLE
vutuv.de/users/{user}/skills_create returns “Page not found” Error

### ISSUE THREAD

**Issue by rosetree** [wintermeyer/vutuv#353]
I just created my vutuv account. The confirmation link in my email, brought me to a “get started” page, asking me to fill in some skills. I enter a few keywords and click on the large button directly beneath the skill input field and get this HTTP 404 error.

**Update**: This is also the case for:
* `/users/{user}/(edit|((work_experiences|phone_numbers|links|addresses)/new))`
* https://www.vutuv.de/api/1.0/users/stefan.wintermeyer/vcard
* https://www.vutuv.de/users/stefan.wintermeyer/links/4
* https://www.vutuv.de/users/stefan.wintermeyer/work_experiences/1

**Comment by ThraaxSession** [comment]
This is duplicate with my ticket. #352

**Comment by wintermeyer** [comment]
Which vutuv account is that? Please include the used URL.

**Comment by ghost** [comment]
Hello,

having the same issue: https://www.vutuv.de/users/kai.korla

regards
Kai

**Comment by rosetree** [comment]
@GinoHereIam ☺ correct. Maybe this issue can be closed. @wintermeyer One URL was https://www.vutuv.de/users/micha.rosenbaum/skills_create Btw I’m really looking forward to use this app, it looks great so far.

**Comment by mattsches** [comment]
Same issue here with https://www.vutuv.de/users/matthias.gutjahr/skills/new and about any other link where I'm supposed to edit stuff.

**Comment by cjfreeze** [comment]
Thanks everyone for reporting this error. A hotfix is rolling out, please let us know if the error is fixed.

**Comment by rosetree** [comment]
@cjfreeze Not yet.

**Comment by cjfreeze** [comment]
@rosetree The second hotfix has rolled out, I am seeing the error fixed on my end. Can you confirm?

**Comment by rosetree** [comment]
@cjfreeze I can now open my edit page, however the `skills_create` page still returns a page not found. The following also return an error page.

* https://www.vutuv.de/api/1.0/users/stefan.wintermeyer/vcard
* https://www.vutuv.de/users/stefan.wintermeyer/links/4
* https://www.vutuv.de/users/stefan.wintermeyer/work_experiences/1

**Comment by cjfreeze** [comment]
@rosetree The skills resource is located at vutuv.de/users/<your_slug>/skills. The skills_create is only programmed to accept a POST reqeust for adding several skills at the same time from the user's profile page, so it won't accept a get request.

**Comment by cjfreeze** [comment]
Closed by 72254b2cd141891573086004d258694551d6db6d

Thanks for everyone's support in fixing this bug!

**Comment by ThraaxSession** [comment]
I just logged out and back in, but the still same issue.

**Comment by ghost** [comment]
Hi,

same Problem. Starting at my page and want to input list of skills. Entering skills and pressing 'Add' results in 'Page not found ' message. See screenshot attached.

regards
Kai
![vutuv-skills-page-not-found](https://cloud.githubusercontent.com/assets/614439/20526157/21141d4c-b0c3-11e6-863b-79d28b86d66c.JPG)

**Comment by cjfreeze** [comment]
@GinoHereIam @balticer Unlike /edit, The /skills_create is not a link that shows a page, but a link for use by the application. The 404 there is intended behavior. To view and edit your skills, please browse to /skills.

**Comment by ThraaxSession** [comment]
@cjfreeze shouldn't behave the frontend different then? I also can't open followers. Only edit my profile works. Looks like 90% of hyperlinks are dead to me. :(

**Comment by cjfreeze** [comment]
@GinoHereIam There is actually another bug. Sorry for the confusion, it was just made apparent to us. Seriously, thanks for your patience. Working on it now. Please post related information in #356
