### ISSUE TITLE
broken layout on Internet Explorer 11

### ISSUE THREAD

**Issue by ghost** [wintermeyer/vutuv#354]
Hello,

see screenshot attached.
![vutuv-broken-layout](https://cloud.githubusercontent.com/assets/614439/20525025/bbd7747e-b0bd-11e6-9d29-6430cce99e28.JPG)

regards
Kai

**Comment by cjfreeze** [comment]
Thanks for reporting this bug, we are looking into it.

**Comment by cjfreeze** [comment]
Assigning this to @cfroerup so his team can take a look at it.
