### ISSUE TITLE
Resources display 404

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#356]

**Comment by ThraaxSession** [comment]
It's not just skills. Also followers, follwing, email editing, social media. Only to edit the main profile part works.

**Comment by cjfreeze** [comment]
@GinoHereIam you are correct, although there was a specifically different error with skills. Give it a shot now.

**Comment by ghost** [comment]
Looks good now!

**Comment by ThraaxSession** [comment]
Great! :)

**Comment by cjfreeze** [comment]
Thanks again for your help!
