### ISSUE TITLE
https://www.vutuv.de/skills - public list?

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#357]
Hi together again,

when I open the link [https://www.vutuv.de/skills](https://www.vutuv.de/skills), I see a list of many skills (I guess all users, but if I click on "Anzeigen", I'll get an internal server error. 

1. Is this link supposed to be public? 
2. I guess the internal server error is also not meant to be.

Regards
Gino

**Comment by wintermeyer** [comment]
It is not a bug but it is not a feature yet either. We are going to add searches for skills. But that is in a later milestone.

@cjfreeze We should fix the CSS for this page and link somehow to search_queries. Botton line: We have to discuss it again in the future.

**Comment by cjfreeze** [comment]
I'm going to disable the routes entirely for now.
