### ISSUE TITLE
Allow to order skills by priority

### ISSUE THREAD

**Issue by rosetree** [wintermeyer/vutuv#358]
It would be great, if I could order my skills by my personal priority. Maybe I’m able to work with both Ruby and PHP, but I like Ruby more and would love to have it before PHP.

Maybe this is similar to the Endorsements in vutuv. But I wouldn’t like, if other could change my choice through their vote.

**Comment by cjfreeze** [comment]
@rosetree You are correct in that the skills are ordered by the number of endorsements received. We have plans for a user preferences feature in the future, this might be one of the preferences we provide. We will be more able to discuss it down the road.

**Comment by wintermeyer** [comment]
Good idea! Let us think about a good solution which is not too complicated in the GUI.

**Comment by wintermeyer** [comment]
Let's add a field `position` (integer) to the model. All SELECTS would have to SORT by that field. In the index view of the skills the owner of the skill should have up- and down-arrows to sort them. But no position field in the form. The value of position should never be displayed.

**Comment by wintermeyer** [comment]
Don't forget that there are existing entries which would be nil. We have to either take care of them as an edge case every time or we have to write a one time migration which fills every field. I think this is the best long term solution but it has to be done very carefully. It's open heart surgery in the production database. Please discuss this migration once it's finished with @wintermeyer.
