### ISSUE TITLE
Delete email icon overlaps edit icon

### ISSUE THREAD

**Issue by mattsches** [wintermeyer/vutuv#359]
I'm using Chrome 54.0.2840.100 (64-bit) on Ubuntu 16.04, and when trying to edit my e-mail address (https://www.vutuv.de/users/username/emails), the icons for editing and deleting the address overlap, cp. gray border around delete on screenshot. When I try to click edit, chances are high I'm actually hitting delete …
![auswahl_448](https://cloud.githubusercontent.com/assets/68414/20527861/41e73bec-b0ca-11e6-9e03-6ff339272046.png)

**Comment by cjfreeze** [comment]
Hi Matt, I'll look into this matter promptly.

**Comment by cjfreeze** [comment]
This is a known webkit bug it seems. Good that it was brought to our attention, so we can watch out for it.

**Comment by cjfreeze** [comment]
I am assigning @cfroerup for some assistance on this issue.
