### ISSUE TITLE
Behavior of multiple accounts from one device and account switching

### ISSUE THREAD

**Issue by DerLordi** [wintermeyer/vutuv#360]
If multiple accounts are created from one device and handled in the following way, then some elements dont work as designed.

How to recreate the Bug:
1. create an account an activate it throuh the gotten email
2. now create a second account and do the same in another tab
3. now switch to the tab from the first account while logged in with the second
4. reload the page

Now you are correctly no longer logged in, BUT some features are still there:
1. The log out Button in the top left corner is still there
2. manually typing .../edit will result in a 403 forbidden site.

This also appears from simple account switching in another tab and reloading the old tab.

Logged out, but still have the chance to log out (top left corner)
![bildschirmfoto 2016-11-22 um 13 43 27](https://cloud.githubusercontent.com/assets/4737847/20528571/0c4ffdfe-b0cd-11e6-82d5-79814ec442d6.png)

When manually adding the /edit link:
![bildschirmfoto 2016-11-22 um 13 43 36](https://cloud.githubusercontent.com/assets/4737847/20528613/34e92cc2-b0cd-11e6-903b-2102b5ff6fdc.png)

**Comment by DerLordi** [comment]
Ok - I missinterpretated the first part. You are logged in with the new account and after switching to the old one, you`re just looking at the profile form the viewport of your new created account and thus have the possibilty to log out from the new account. Works as designed, so no bug there. 

The second part (403 forbidden) should result into a user friendly error page.

**Comment by cjfreeze** [comment]
Thanks for the sleuthing! We're aware of our terrible error pages (sorry!) and are working on it.
https://github.com/vutuv/vutuv/issues/355

Do let us know what else you find!
