### ISSUE TITLE
Entering a partial adress in profile editing results in a 500 Error page

### ISSUE THREAD

**Issue by DerLordi** [wintermeyer/vutuv#361]
When adding a Adress to your personal profile and do not fill all fields, then after hitting send, the page will return a 'server internal error' page. 

Working validations are here in order and the marking of required fields.

**Comment by wintermeyer** [comment]
Thanks for the bug report. @cjfreeze will take care about it in the next 72 hours.

**Comment by cjfreeze** [comment]
Thanks for your contribution to vutuv, @DerLordi!
