### ISSUE TITLE
RSS feed and ical export for birthdays

### ISSUE THREAD

**Issue by stephriedel** [wintermeyer/vutuv#363]
Als Anwender möchte ich einen RSS-Feed der aktuellen Geburtstage meiner "Followers/Following" erhalten.

en: An RSS Feed of the next birthdays (Followers/Followees). We could even do an ical export.

**Comment by wintermeyer** [comment]
Das ist eine brillante Idee! Kommt auf die Roadmap. Ich übersetze gleich den Text ins Englische.

**Comment by linux-lukas** [comment]
Could it perhaps be kept more general and perhaps combined with anActivityPub connection from Vutuv so that the profiles could be subscribed to via RSS, @wintermeyer ?

**Comment by wintermeyer** [comment]
Yes, that would be nice. But to be honest: There are bigger fish to fry right now.
