### ISSUE TITLE
Idea, sticky header

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#364]
Hi,

what do you think about it if you scroll down and the header decrease its size and stays sticky on the above viewport with the profile pic and job description?

Regards
Gino

**Comment by cjfreeze** [comment]
It sounds good from a visual perspective, but would be a challenge to accomplish with our _modus operandi_ of no javascript.

**Comment by ThraaxSession** [comment]
@cjfreeze just an idea.. probably it works already with CSS. :D
