### ISSUE TITLE
Trim job title @ company to a max. size

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#367]
It should be made sure that the sting of job title @ company is not longer than it makes sense CSS wise. It shouldn't be longer than this example:

![bildschirmfoto 2016-11-22 um 19 40 18](https://cloud.githubusercontent.com/assets/69770/20536976/96620d70-b0eb-11e6-88de-4e32ca78d1a1.png)

**Comment by cjfreeze** [comment]
Closed in a754e42f02836ce7310eea06fc57b75e62e5dbf1
