### ISSUE TITLE
Mr or Herr is not a good default on the index page

### ISSUE THREAD

**Issue by webmatter** [wintermeyer/vutuv#368]
Ein voreingestelltes "Herr" bei der Registrierung irritiert. Da es ganz sicher nicht an einer alphabetischen Sortierung liegt, fühle ich mich als Frau nicht unbedingt angesprochen. Soll das eine Herrenplattform werden?

en: To have "Mr" or "Herr" as the default in the new user registration form doesn't make any sense. It shouldn't have any default. The autofocus has to be changed to this field.

**Comment by wintermeyer** [comment]
Guten Morgen @webmatter, erst mal Danke für den Bugreport. Machen wir es kurz: Es ist ein Fehler das "Herr" der Default ist. Das ist auf meinem Mist gewachsen. Sorry! Ich werde das Ticket gleich ins Englische übersetzen. Wir werden es im Laufe des Tages fixen.

**Comment by cjfreeze** [comment]
This was closed in 09021004e76e67988579a7d1c028e8099298d71a

**Comment by wintermeyer** [comment]
Autofocus hasn't been changed to this field.
