### ISSUE TITLE
Email address has two status

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#371]
Hi,

I just figured out, when I go to edit my email address, there it is private as I wished. If I go to edit my headline, I see it's public there. 

Regards
Gino

**Comment by wintermeyer** [comment]
Currently you can set permissions on the email address and on the visibility for search engines. We will break up the permission system in Milestone 2.0. Then you'll be able to define who can see what.

**Comment by ThraaxSession** [comment]
If I remember right, I read yesterday "who is able to see your profile in public" ... maybe it went lost with translation. Now there is written about email: [https://www.vutuv.de/users/gino.atlas/edit](https://www.vutuv.de/users/gino.atlas/edit)
"Ist diese E-Mail Adresse privat oder öffentlich?"
