### ISSUE TITLE
Better <title> and <meta .. description ...>

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#372]
Currently the page https://www.vutuv.de/users/stefan.wintermeyer has this information in the HTML header:

```html
<title> Stefan Wintermeyer </title>
<meta name="description" content="">
```

But it should have this information:

```html
<title>Stefan Wintermeyer || vutuv profile</title>
<meta name="description" content="Geschäftsführer @ AMOOMA GmbH. Skills: WebPerformance, Ruby on Rails, Elixir, Phoenix">
```

This should be gettexted where possible (e.g. "vutuv profile").

There is a follow up issue (https://github.com/vutuv/vutuv/issues/340) where we have to dig deeper into the SEO part.

**Comment by cjfreeze** [comment]
I'm guessing you only want it to say vutuv profile on the vutuv profile?

**Comment by wintermeyer** [comment]
Yes, only on the profile page.
