### ISSUE TITLE
Missing title and company

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#374]
Have a look at https://www.vutuv.de/users/kai.korla

![bildschirmfoto 2016-11-23 um 09 45 11](https://cloud.githubusercontent.com/assets/69770/20555314/a9e0fd9a-b161-11e6-9abd-3502b2c8bc4c.png)

Under his name should be what he does. But there's nothing. Could it be that the missing start date of the work experience is the problem?

![bildschirmfoto 2016-11-23 um 09 45 20](https://cloud.githubusercontent.com/assets/69770/20555323/b63ee318-b161-11e6-8e27-5a3567715b35.png)

**Comment by cjfreeze** [comment]
The `current employment` function searches for a job with a start date, and no end date, so yes the missing start date is the culprit here.
