### ISSUE TITLE
Uniformly skills would be nice

### ISSUE THREAD

**Issue by DerLordi** [wintermeyer/vutuv#377]
I think that it would be better in the long term to unify skill names. Maybe choose skills from a list with autocomplete like stackoverflow does with tags (i realise that this is a problem because of the no-javascript-rule).

Or match skill names on the server with a fuzzy logic or something like that, after creation. So it would be prevented that skills like 'Ruby on Rails', 'Ruby on Rails Framework' are two different ones.

**Comment by wintermeyer** [comment]
I'm aware of this issue. We are going to tackle it in Milestone 2.x.
