### ISSUE TITLE
Store Public Keys

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#380]
Let's discuss if it makes sense to store public keys and if yes how we can do this.

**Comment by morph027** [comment]
Absolutely!

For a start, why not just adding a key fingerprint / hash as text value and create an url if a link to a keyserver/keyfile was provided?

**Comment by wintermeyer** [comment]
Good idea.

**Comment by morph027** [comment]
Sure it only would be necessary in combination with a mail address ;)

Probably inside brackets beneath the address?
