### ISSUE TITLE
Uebersetzungen

### ISSUE THREAD

**Issue by gasserol** [wintermeyer/vutuv#382]
Hallo, sollten Sie italienische und französische Übersetzungen brauchen, könnten wir helfen :-) Wir haben unsere Firma in der italienischen Schweiz (Tessin) und ich habe lange auf französisch gearbeitet.. dies nur zur Info.

**Comment by wintermeyer** [comment]
Vielen Dank für das Angebot! Ich komme darauf gerne zurück. Allerdings erst in ein paar Wochen. Aktuell ist noch zu viel in Bewegung. Zu viele Texte ändern sich. Wenn da Ruhe eingekehrt ist, dann würde ich mich über Hilfe bei der Übersetzung freuen. Ich setzte das mal auf Milestone 2.0.
