### ISSUE TITLE
Consistency - email visibility - German translation

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#383]
Hi together,

there is a little inconsistency in email visibility,
contacts: "Privat"
common profile: "Private"

Update:
common profile: https://www.vutuv.de/users/gino.atlas/edit
contacts: https://www.vutuv.de/users/gino.atlas/emails

Regards
Gino

**Comment by wintermeyer** [comment]
Which URLs?

**Comment by cjfreeze** [comment]
I see the bug, it will be fixed shortly.
