### ISSUE TITLE
Change magic link to base 16

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#386]
Please add === if a magic link is missing it. I just got a big report with a screenshot. Some clients just don't see the === as part of the link.

**Comment by ghost** [comment]
I think this is because the mail is plain text and buggy mail clients (such outlook) don't realize that '===' belongs to the full url. IMO a possible option is to change the magic link somehow that it is alphanumeric only (except special chars).

**Comment by cjfreeze** [comment]
Closed in 8d9ed012844a8c4e552b0bba5013f27d1e0d7c3a
