### ISSUE TITLE
Office 365 considers vutuv to be spam.

### ISSUE THREAD

**Issue by oliverandrich** [wintermeyer/vutuv#387]
I checked with my company which is using office 365 and they confirmed that vutuv is always treated as spam by the office 365 spam filter. There is no way to configure it for the admins. You need to contact Microsoft about that.

**Comment by wintermeyer** [comment]
Thanks for the great debugging! Now that we now it we can give this information to the user on the webpage. Not ideal but better than nothing.

**Comment by firstinstance** [comment]
Hi schau mal hier:
https://www.mail-tester.com/web-6l6hu
Ich denke, wenn man einen SPF Header konfiguriert sollte das Problem behoben sein.
Viele Grüße
Simon

**Comment by wintermeyer** [comment]
@firstinstance Danke für diesen Tipp! Ich habe den SPF Header eingetragen.

I created an SPF header.
```
06:34 $ dig +short TXT vutuv.de :
"v=spf1 mx a ip4:89.221.1.56 a:virusgate.antilo.de ~all"
```

 I close the issue for now.  If the problem comes up again we have to reopen it.

**Comment by wintermeyer** [comment]
@firstinstance Bitte schicke mir eine E-Mail mit Deinem vutuv Account. Dann verifiziere ich ihn.

**Comment by firstinstance** [comment]
Hi @wintermeyer, hast du schon. Ich bin Simon :-)
Den Account mit der Adresse web-6l6hu@mail-tester.com kannst du wieder löschen. Der war nur fürs Debuggen. Viele Grüße, Simon

**Comment by wintermeyer** [comment]
Würde es Dir was ausmachen den Account selbst zu löschen. Ich würde gerne wissen, ob das richtig funktioniert. Da gab es auch ein Bug.
