### ISSUE TITLE
Display error on mobiles

### ISSUE THREAD

**Issue by oliverandrich** [wintermeyer/vutuv#388]
The string in the top left corner is cut off.

**Comment by oliverandrich** [comment]
![img_6238](https://cloud.githubusercontent.com/assets/758/20567436/f71fb2b8-b198-11e6-94e3-8c795f4b2f3e.PNG)

**Comment by wintermeyer** [comment]
I've seen this problem. Thanks for creating the issue. I'm not sure when we'll find the time to fix it. It's low priority.

Side-story: The guy who wrote the CSS used the english term "login" which is smaller and therefor works. ;-)
