### ISSUE TITLE
Fehler bei Klick auf Skills

### ISSUE THREAD

**Issue by webmatter** [wintermeyer/vutuv#389]
![fehler](https://cloud.githubusercontent.com/assets/3080157/20574005/cd8bcb5c-b1b2-11e6-86a2-c2821561882a.png)

p.s. irgendwie fehlt auf der Plattform Interaktionsmöglichkeit und Content ... also wenn man mal vom Erstellen eine Profils absieht (?)

**Comment by wintermeyer** [comment]
Welche URL ist das?

**Comment by webmatter** [comment]
Komisch, jetzt ist es weg. Es war diese URL (bzw. erschien bei Klick auf alle Skills)
https://www.vutuv.de/users/wolfgang.merkel1/skills/558
