### ISSUE TITLE
Icons are to close

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#390]
Hi,

the icons on the CV are to close:
![bildschirmfoto von 2016-11-23 19-30-10](https://cloud.githubusercontent.com/assets/3085830/20574122/5ba40fc6-b1b3-11e6-849b-0f1b7682cd93.png)

btw, how to become a veryfied person? :D

Regards
Gino

**Comment by wintermeyer** [comment]
Thanks for the input. We take care of that down the road.

**Comment by wintermeyer** [comment]
Wish granted. :-)

**Comment by ThraaxSession** [comment]
Hihi thanks Stefan! :D
