### ISSUE TITLE
Text encoding issue on impressum.html

### ISSUE THREAD

**Issue by hjacobs** [wintermeyer/vutuv#392]
See screenshot
![screenshot_2016-11-23_19-54-48](https://cloud.githubusercontent.com/assets/510328/20574831/c6fe7eac-b1b6-11e6-818d-003ce3610d30.png)

**Comment by hjacobs** [comment]
Looks like missing `meta` tag or `charset=utf-8` in `Content-Type` header?

**Comment by wintermeyer** [comment]
We are aware of that problem. I totally underestimated how many people visit that page. Will fix it in the next couple of days. Thanks for the bug report!
