### ISSUE TITLE
Add GnuSocial to social media providers

### ISSUE THREAD

**Issue by stenbuk** [wintermeyer/vutuv#393]
I'm missing (open source) GnuSocial as social media provider selection.

**Comment by cjfreeze** [comment]
We're taking suggestions for these to add in the near future, expect this one to be added! : )

**Comment by stenbuk** [comment]
Thanks. :)

**Comment by wintermeyer** [comment]
I'm closing this issue and adding GnuSocial to the issue https://github.com/vutuv/vutuv/issues/396
