### ISSUE TITLE
Don't display a too long string for name

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#394]
![bildschirmfoto 2016-11-23 um 20 22 26](https://cloud.githubusercontent.com/assets/69770/20575711/b9fa3562-b1ba-11e6-83b4-f48aca701a62.png)

Let's discuss how we can tackle that problem.

**Comment by cjfreeze** [comment]
We could also cut off names... but why does he have his job title in his name?

**Comment by ghost** [comment]
It's not the job title. It seems that is the academic degree.

**Comment by MichaelBiermann** [comment]
Similar issue regarding cut off User data, see https://github.com/vutuv/vutuv/issues/435
