### ISSUE TITLE
vcard-Download

### ISSUE THREAD

**Issue by Wildvirus** [wintermeyer/vutuv#395]
After click on "Vcard Download" I received a file "vcard". The suffix .vcf is missing. 

In the file are not all attributes filled. In the line with the label-attribute the separator : is missing
and at the end is a missing attribute: REV:TIMESTAMP NOT YET IMPLEMENTED

**Comment by wintermeyer** [comment]
Thanks for the bug report. We'll fix it in the next 48 hours. It gets priority.

**Comment by cjfreeze** [comment]
Closed in ab3386955a8a3159934d7ab4411bfb6ade23cd7e

**Comment by Wildvirus** [comment]
Wow - Sehr schnelle Änderung. 

Klappt auch gut, nur ein kleiner Fehler noch in Zeile 24

` "\nLABEL;TYPE=WORK"<>sanitize(f.lin`

es fehlt der Doppelpunkt hinter WORK
` "\nLABEL;TYPE=WORK**:**"<>sanitize(f.lin`

und die Codepagecodierung klappt nicht. In meinem Profil steht als Ort Köln, beim Import der Datei nach Outlook kommt "KÃ¶ln" an. (Aus ADR;TYPE=WORK:). Outlook nutzt CHARSET=Windows-1252

Wenn ich den Fehler aus Zeile 24 korrigiere, liest Outlook die Straße ein, aber nicht PLZ und Ort. 

Das Bild kommt auch nicht beim Import an. 

Import auch mit IBM Notes getestet, gleiches Ergebnis, nur Adresse kommt gar nicht an.
