### ISSUE TITLE
Add Social Media Providers

### ISSUE THREAD

**Issue by Wildvirus** [wintermeyer/vutuv#396]
pls. add 
LinkesIn
Xing
Google Plus

**Comment by wintermeyer** [comment]
@cjfreeze Let's discuss this list tomorrow.

**Comment by wintermeyer** [comment]
GnuSocial as mentioned in https://github.com/vutuv/vutuv/issues/393

**Comment by wintermeyer** [comment]
To make things more complicated we should try to import already entered data. Example:

https://www.vutuv.de/users/holger.milde

![bildschirmfoto 2016-11-26 um 12 11 18](https://cloud.githubusercontent.com/assets/69770/20639931/99310400-b3d1-11e6-9f24-b44732c4af70.png)

He linked to his XING Account. We should scan these links and convert them to social media accounts. The old links should be deleted.

**Comment by stenbuk** [comment]
@wintermeyer It's too bad, that the only open source "provider" GnuSocial wasn't considered and added. :/

**Comment by wintermeyer** [comment]
GnuSocial hasn't the community size to be listed yet. There are too many social media networks out there. We can not list every one. But thanks for the input!

**Comment by 85pando** [comment]
@stenbuk GnuSocial is not the only open source social network, there is also [diaspora](https://www.joindiaspora.com/)

**Comment by stenbuk** [comment]
@85pando Sorry, you're right. Let's say "Fediverse" and Diaspora.

**Comment by 85pando** [comment]
@stenbuk Nevermind, but as we go along we might also want to rqquest [Mastodon](https://mastodon.social/about)?

**Comment by stenbuk** [comment]
@85pando I thought, Mastodon is part of Fediverse as it's gnusocial compatible. 
But i think, the term i was looking for is OpenMicroBlogging/OStatus implementing/supporting networks.

**Comment by joker234** [comment]
I searched for a possibility to add a fediverse (Mastodon/GnuSocial/?) account, too. I note a growing community using Mastodon in my environment.

Isn't it possible to add a Field like “Fediverse” where one can add his Identifier (the internal syntax of Mastodon is @username@instance, e.g. @joker234@chaos.social or as an alternative https://instance/@username e.g. https://chaos.social/@joker).

According to Wikipedia, [Mastodon has reached 766,500 users](https://en.wikipedia.org/wiki/Mastodon_(software)#Function). Additionally the users of other [OStatus](https://en.wikipedia.org/wiki/OStatus) compatible instances. Isn't that enough?
