### ISSUE TITLE
Suchfunktion

### ISSUE THREAD

**Issue by Wildvirus** [wintermeyer/vutuv#397]
Im Moment ist die Suchfunktion nur für Namen möglich. Suche nach Firma und/oder Fähigkeiten wäre auch sinnvoll

**Comment by julkue** [comment]
As far as I can see this isn't German-specific: English, please?

**Comment by cjfreeze** [comment]
@julmot We accept issues in German or English.

**Comment by julkue** [comment]
Whoops, then I have set my star accidentally.

**Comment by cjfreeze** [comment]
@Wildvirus We have an issue open to expand the search feature. #339
