### ISSUE TITLE
Datenschutzerklärung

### ISSUE THREAD

**Issue by Wildvirus** [wintermeyer/vutuv#399]
Die Erklärung ist nur auf Englisch und hat ein anderes Aussehen als die Hauptseite selbst und keinen Link zurück zur Hauptseite

**Comment by cjfreeze** [comment]
Are you referring to the [privacy policy?](https://www.vutuv.de/privacy-policy.html) If so, there is an existing issue to improve it. #320

**Comment by Wildvirus** [comment]
@cjfreeze Yes that's the page

**Comment by wintermeyer** [comment]
It's a known issue that will be dealt with during the next milestone. Thanks for your report.
