### ISSUE TITLE
Fähigkeiten

### ISSUE THREAD

**Issue by Wildvirus** [wintermeyer/vutuv#400]
Bei den Fähigkeiten gibt es den Daumen hoch, anschließend steht bei deutscher Einstellung "1 Upvote". Vorschlag ändern auf "Bestätigung" bzw. ab zwei auf "Bestätigungen"

**Comment by julkue** [comment]
English, please?

**Comment by Wildvirus** [comment]
@julmot - It is about a mistake in the german website, therefore german post
