### ISSUE TITLE
Englische Startseite

### ISSUE THREAD

**Issue by Wildvirus** [wintermeyer/vutuv#402]
Beim Aufruf mit Firefox 50 unter Ubuntu 16.04 LTS wird die Startseite in Englisch angezeigt, obwohl Ubuntu auf Deutsch läuft. 

Nach Anmelden kommt die Bestätigungszeile, dass ich angemeldet wurde, auch kurz auf Englisch und verschwindet. Weitere Meldungen bzw. Oberfläche sind in Deutsch. 

Nach Abmeldung erscheint wieder englische Seite 
![ubuntu 16](https://cloud.githubusercontent.com/assets/9499201/20577311/ffaad68c-b1c1-11e6-817b-d1d5c535a52c.png)

**Comment by wintermeyer** [comment]
We use the browser language setting. Being a Debian guy I'm not familiar with the details of the Ubuntu desktop and how they handle the language settings. Probably it's not a vutuv bug.

I'll keep an eye on this potential problem the next couple of days.
