### ISSUE TITLE
Some resources can be opened from the context of a user who isn't the owner.

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#403]
Hi,

something totally weird. When I opened a job title of my own, I see as specific number
e.g. 27
when I change it too for e.g. 20, I see a totally different job title to my profile!
[https://www.vutuv.de/users/gino.atlas/work_experiences/27](https://www.vutuv.de/users/gino.atlas/work_experiences/27)
[https://www.vutuv.de/users/gino.atlas/work_experiences/20](https://www.vutuv.de/users/gino.atlas/work_experiences/20)

Regards
Gino

**Comment by cjfreeze** [comment]
While this can happen... it can't happen on private resources and doesn't really affect much. It will be fixed but is not a priority.
