### ISSUE TITLE
Title on own profile without "@ company"

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#405]
Hi,

I just figured out, when I look at other profiles I see under the name "job title @ company". But on my own profile there is only "job title", is this planned?

Regards
Gino

**Comment by cjfreeze** [comment]
It's has to do with the length of the text. Right now we've set a hard length, and if your `job title @ organization` text exceeds that, it tries to shorten it to prevent bad behavior of the UI. First it removes the organization. It is correct behavior, and is temporary until we can have the CSS do this for us.
