### ISSUE TITLE
Searching returns with weird findings

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#406]
Hi,

I just searched for "Heinz" and got a lot of unreasonable finding.

Regards
Gino

**Comment by cjfreeze** [comment]
Ah, the logic behind this has to do with phonetic algorithms.

Using the Cologne Phonetics algorithm, `Heinz` and `Johannes` evaluate to the same phonetic code, in this case `068`. That means that while they aren't the same, they sound similar enough to show up in a search. Everything is behaving properly.

**Comment by ThraaxSession** [comment]
Sorry, in what way do they sound similar? :D
