### ISSUE TITLE
advertising should open in new tab

### ISSUE THREAD

**Issue by Wildvirus** [wintermeyer/vutuv#407]
on my profile is advertising ad for AMOOMA, The click on it open the url in the same tab. 

I would prefer to use a new tab

**Comment by wintermeyer** [comment]
Thank you for the feature request. 
I am not a big fan of new tabs for everything. I am a believer in the back button each browser has. Sorry!

**Comment by Wildvirus** [comment]
perhaps an enhancement for a feature "preferences" ?

**Comment by wintermeyer** [comment]
I'll think about it.
