### ISSUE TITLE
email notification (status update for new followers)

### ISSUE THREAD

**Issue by ddeimeke** [wintermeyer/vutuv#409]
Please add email notifications for new followers.

**Comment by wintermeyer** [comment]
That's a tricky one. I don't want vutuv users to be flooded by emails like it is the case with LinkedIn or XING. I might add a configuration option for this in the future. Let's discuss this again during Milestone 2.0.

Thanks for the input!

**Comment by ddeimeke** [comment]
I totally agree. A configuration option would be great.
