### ISSUE TITLE
Please consider adding work mobile numbers as well

### ISSUE THREAD

**Issue by ddeimeke** [wintermeyer/vutuv#410]
It would be nice to have any phone number for work AND home.

Home / work mobile
Home / work landline
Home / work fax (don't know if fax is still needed)

**Comment by wintermeyer** [comment]
Good point! Thanks for the input.

@cjfreeze: Let's discuss this in Milestone 1.2

**Comment by ddeimeke** [comment]
If I remember correctly, one version of the vCard-format has only standard fields, which are the ones you implemented.
