### ISSUE TITLE
idea, changelog for vutuv changes

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#413]
Hi,

it might be an idea, how to add a link to a changelog what's happening here? :) It's interesting how the platform is growing and changing. 

Update:
With every deployment you could attach a simple `changelog.txt` by `git log --oneline --decorate --ignore-space-change`

Regards
Gino

**Comment by wintermeyer** [comment]
Good idea. Let me sleep a night over it. I'll figure something out. But not in the next couple of days.
