### ISSUE TITLE
Translation error - valdidating phone number

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#415]
Hi,

there is a translation issue when I entered a wrong phone number sytanx: `Please enter a phone number`

Regards
Gino

**Comment by wintermeyer** [comment]
I'll take care of this in the next 48 hours.

**Comment by wintermeyer** [comment]
It doesn't get gettexted.

`web/models/phone_number.ex`
```
  @format_message ~s/Please enter a phone number/
  @requred_message ~s/This field is required/
```
