### ISSUE TITLE
Man sollte Einträg auch löschen können.

### ISSUE THREAD

**Issue by FauthD** [wintermeyer/vutuv#419]
Bei Skills habe ich beim zweiten Male auch mehrere Einträge mit KOMMA eingegeben. Diese werden jetzt als ein Skill dargestellt und können nicht gelöscht/verändert werden.
Andere Einträge bei Skills haben den X.
https://www.vutuv.de/users/dieter.fauth/skills

Wenn man auf die Zeile (mit den Kommas) clickt, geht es zu einer neuen Seite mit X, aber X führt zu "Page not found".
https://www.vutuv.de/users/dieter.fauth/skills/6627

**Comment by wintermeyer** [comment]
Können Sie bitte einen Screenshot der Seite https://www.vutuv.de/users/dieter.fauth/skills hinzufügen?

**Comment by FauthD** [comment]
Sure,
I start with overview screen (OverviewScreen.png), 
![overviewscreen](https://cloud.githubusercontent.com/assets/19874899/20617774/a65f07f8-b2eb-11e6-9314-a411438bbd77.png)
click on "Alles anzeigen" (=show all) (skills.png),
![skills](https://cloud.githubusercontent.com/assets/19874899/20617783/ae0ad0ea-b2eb-11e6-9c70-1b42acd18902.png)
you can see the skills with comma separated (I expected it works like with the very first entry that parses and separates them).
Now click on line with text "Integration, ....".
Next pages tells there is noting to see (in German):
![nothingtosee](https://cloud.githubusercontent.com/assets/19874899/20617832/fbc466e8-b2eb-11e6-8af7-25db8a61cc0e.png)
Clicking on the red X leads to a 404 page
![page6627](https://cloud.githubusercontent.com/assets/19874899/20618126/c23ef29c-b2ed-11e6-8d70-cdc41c9f7485.png)
 (kind off).

I hope this helps.
