### ISSUE TITLE
Add languages a user speaks

### ISSUE THREAD

**Issue by FauthD** [wintermeyer/vutuv#420]
Mann könnte Sprachen auch bei Skills unterbringen, aber es ist besser diese mit Feldern anzugeben:
Anfänger, ... Verhandlungssicher.

en: It would be a good idea to have a way to store the language a user speaks and a criteria how good he/she speaks it.

**Comment by wintermeyer** [comment]
Sprachen ist eine sehr gute Idee! Ich werde das mal ins Englische übersetzen und im nächsten Meilenstein im Team besprechen.

**Comment by wintermeyer** [comment]
The criteria could be a number from 1 to 10. 10 being a native speaker and 1 knowing maybe a couple of words.

**Comment by wintermeyer** [comment]
This needs to be a scaffold with a slug. We should store the languages as one model and fill it initially with the main languages (or whatever we can find without much work). I don't want the user to enter the name of a language manually. He/She should should from a dropbox. That makes it easier to filter later.
