### ISSUE TITLE
YouTube Link Examples

### ISSUE THREAD

**Issue by Phlow** [wintermeyer/vutuv#421]
Die generierten YouTube-Links können so aussehen:

https://www.youtube.com/c/phlow
https://www.youtube.com/user/PhlowMedia

Natürlich auch so:
https://www.youtube.com/channel/UCJ0uqCI0Vqr2Rrt1HseGirg

Ich würde es den Nutzern überlassen, welche Art von Endung sie nutzen.

**Comment by wintermeyer** [comment]
Danke für den Input. Wir werden das im nächsten Meilenstein im Team besprechen.

**Comment by MichaelBiermann** [comment]
Auf dem iPad kam bei mir noch hinzu, dass ich bei Youtube überall die email-Addresse zum Account gesehen habe, aber nirgends den User. Umschalten auf die Desktopversion war dann die Lösung.

**Comment by wintermeyer** [comment]
Bitte mache mal einen Screenshot davon auf dem iPad und füge das zum Issue hinzu.

**Comment by MichaelBiermann** [comment]
Bei Youtube habe ich auf dem IPad lange gesucht, um die User Id zu finden. In die Desktopversion wechseln und dann das eigene Bild anklicken und die URL beobachten ... 'youtube.com/user' in Chrome eingegeben hat bei mir direkt youtube.com/user/MichaelBiermann angezeigt.
![img_0550](https://cloud.githubusercontent.com/assets/489600/20636156/17f7e5e8-b368-11e6-9313-c38ac2a432fb.PNG)

![img_0551](https://cloud.githubusercontent.com/assets/489600/20636160/3727baba-b368-11e6-8826-87ee43b373dd.PNG)
