### ISSUE TITLE
Searching for C# brings to result

### ISSUE THREAD

**Issue by faulandcc** [wintermeyer/vutuv#425]
Hi there,
first congratulations to your product. Great to see a new networking tool coming up!
I created my profile and now if I search for other C# devs I don't get any results. At least my very own profile might show up in the search result.

Thanks and cheers, 
Alexander

**Comment by wintermeyer** [comment]
The search functionality currently only works for names and email addresses. We underestimated the need for a skill search. It is on a high priority and will be available in the next 14 days.

**Comment by faulandcc** [comment]
Great, thank you!!
