### ISSUE TITLE
Following list is cut off

### ISSUE THREAD

**Issue by ThraaxSession** [wintermeyer/vutuv#426]
Hi,

the list [https://www.vutuv.de/users/stefan.wintermeyer/followees](https://www.vutuv.de/users/stefan.wintermeyer/followees) is just cut off, even the list is longer.

Regards
Gino

**Comment by wintermeyer** [comment]
@cjfreeze works on a pagination system. Until than we cut of this list. It doesn't make sense to display 2,000 accounts on one page. See https://github.com/vutuv/vutuv/issues/308
