### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by emmi59** [wintermeyer/vutuv#427]
Hi, folks

After creating a new account (on PC) and clicking the link in the email (on my SmartPhone) I am unable to log in to my account on the PC. It always directs me to the "new" page and tells me to check my email.
Should be fixed because I cannot open my email from the PC (at work) and will not use vutuv on my SmartPhone.

Kind regards

Uwe Emmrich-Kießling

**Comment by wintermeyer** [comment]
Please logout. Clean the browser cache and login again. This might just be a cache problem. 
https://www.vutuv.de/sessions/new

Please tell me if it worked. Than I'll verify your account.

**Comment by emmi59** [comment]
Hi

since I have never been logged in on the PC - how should that work?

And I logged out on the Smartphone too.

Kind regatds

uek

Uwe Emmrich-Kießling



On Thu, Nov 24, 2016 at 3:21 PM +0100, "Stefan Wintermeyer" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #427<https://github.com/vutuv/vutuv/issues/427>.
