### ISSUE TITLE
Add Contact field label "Value" should probably read "Email"

### ISSUE THREAD

**Issue by flat235** [wintermeyer/vutuv#428]
Maybe it's intended to mean contact information besides email, but it's not clear.
If you mean "any contact information" the label should probably say something like that.

Great project btw :)

**Comment by wintermeyer** [comment]
Thanks! Would you mind to add a screenshot or a URL?

**Comment by flat235** [comment]
url: https://www.vutuv.de/users/moritz.bellach/emails/new

![screenshot_vutuv](https://cloud.githubusercontent.com/assets/3152820/20603552/51cb5aea-b262-11e6-8030-9e6579de8d16.png)

**Comment by wintermeyer** [comment]
Your right. Thanks for the feedback. Fix is on the way.
