### ISSUE TITLE
Clicking on the "vutuv" heading shouldn't log you out

### ISSUE THREAD

**Issue by flat235** [wintermeyer/vutuv#429]
This is really unexpected behaviour, please redirect either to the users profile or somewhere else, but do not log the user out for trying to get back to the "main" page from some submenu.

**Comment by wintermeyer** [comment]
Are you sure this is not a browser cache problem? Can you logout, clear the cache and log in again?

**Comment by flat235** [comment]
I just tried to reproduce the problem and can't. Unfortunately I don't remember from which page I tried this, but any page I can reach works fine now. So, yes, it may be an issue that's only present after the first login, or it may have something to do with my computer. Sorry for not being able to track this down.
If this reoccurs: Browser is chromium-54.0.2840.100 (gentoo linux version).

PS: Great response time :)

**Comment by wintermeyer** [comment]
Thanks! :-)
