### ISSUE TITLE
Recommendation system for new users

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#430]
Now that we get more users I can't auto follow every new user. We need some sort of automated recommendation system where new users find a card with potential interesting users for them. If we don't know anything about the user we just have to display popular accounts with the same language. But as soon as the user enters skills we can create better recommendations.

This system needs to be helpful and not annoying.

**Comment by ThraaxSession** [comment]
Maybe same company would be nice too, I was already surprised to find someone there too. :D
