### ISSUE TITLE
Woher komme ich

### ISSUE THREAD

**Issue by chefrocker** [wintermeyer/vutuv#432]
Man erkennt nur schwer, woher der Benutzer kommt, könnte man da nicht eine Rubrik machen, mit einer ungefähren Region? Ich möchte nicht jedem hier auf diesem Profil meine Private Adresse freigeben. Man könnte auch die Arbeitgeber mit Adresse hinterlegen, so hätte man einen ungefähren Standort

**Comment by wintermeyer** [comment]
Im Meilenstein 2 werden wir ein Rechtssystem einführen, mit dem man zwar seine Adresse eingeben kann, aber sie sonst keiner lesen kann. Oder (und das ist mein Lieblingsfeature) nur die eigene Familie oder Freunde. Das wird aber noch ein paar Wochen dauern.

Danke für das Feedback!
