### ISSUE TITLE
Trouble authenticating additional e-mail address

### ISSUE THREAD

**Issue by bad** [wintermeyer/vutuv#434]
I just tried to add an additional e-mail address to my vutuv account bad@bsd.de.
The the authentication mail with he magic link (sent 18:52 CET) arrived on my smart phone.
However, touching the magic link transfers me to the account creation page on vutuv (Ihr neuer Account ist in 30 Skunden fertig. [Geschlecht], [Vorname], [Nachname] [E-Mail-Adresse])
Filling in the form fields with the same info as the main account except for the e-mail address (I used the just-added address) gives me "has already been taken" (Note the English error message on the German UI).

Hmm, now I have received another magic link at bad@bsd.de after opening that in the browser the added e-mail address was approved.
Unfortunately I can't tell what caused the link to be sent.  I made an earlier attempt giving my "main" address in the e-mail address field. It could have been sent by that attempt.

In any event I'd like to say that in either case not clearly telling me that an authentication link has been sent is very counter intuitive behaviour.  And producing an error like "has already be taken" in response to the magic link for the correct address even more so.

The smart phone is a Nexus 5 with up-to-date apps. Specifically Chrome as the web browser.

But thanks for the good work!

**Comment by cjfreeze** [comment]
So sorry to hear about this issue. We'll work on reproducing and fixing it in the next 48 hours.

**Comment by cjfreeze** [comment]
@bad I believe we have a fix in an upcoming release, but let me know if you encounter this error again. Thanks for helping us improve vutuv!
