### ISSUE TITLE
'Ausloggen' too long -> see screenshot

### ISSUE THREAD

**Issue by MichaelBiermann** [wintermeyer/vutuv#435]
Vutuv works great in general, love it.

Minor issues:
-  'Ausloggen' too long -> see screenshot
- 'Developer - Enterprise Search' cut of, even if there is room for more characters

![screenshot_2016-11-25-00-08-19-094_com brave browser](https://cloud.githubusercontent.com/assets/489600/20611150/fee98570-b2a4-11e6-9fbc-ef5aea3ba9f4.png)

**Comment by MichaelBiermann** [comment]
The first part is alread meantioned here: https://github.com/vutuv/vutuv/issues/388 .
The second part is close to https://github.com/vutuv/vutuv/issues/435.
Feel free to close this issue after reviewing the screenshot.

**Comment by cjfreeze** [comment]
The cutoff is a temporary fix until we finish a more robust solution. We are aware of this shortcoming and are working to improve it :)
Thanks for helping to improve vutuv with us!
