### ISSUE TITLE
Error message for portrait mode of smartphones #search

### ISSUE THREAD

**Issue by MichaelBiermann** [wintermeyer/vutuv#436]
When searching w/o searchterms, you get an error message.
Improve the look&feel of error message for portrait mode of  smartphones -> see screenshot

![screenshot_2016-11-25-00-43-58-420_com android browser](https://cloud.githubusercontent.com/assets/489600/20611361/26674ba6-b2a9-11e6-878e-311a3fa77c53.png)

**Comment by wintermeyer** [comment]
I removed the search result part because that is already a known problem. We will take care of that.
