### ISSUE TITLE
Pleas show all current assignments in the CV section

### ISSUE THREAD

**Issue by ddeimeke** [wintermeyer/vutuv#437]
It would be nice to see (at least) all current assignments in the CV (experiences) section of a profile page. 

At the moment I see "only" three.

In case this is not possible it would be great to have an option - "show on front page" - to configure the behaviour.

**Comment by wintermeyer** [comment]
Thanks for the input. We will work on this problem today or next week. I close this issue and attach some information to issue https://github.com/vutuv/vutuv/issues/438
