### ISSUE TITLE
Donate ... an alternative or addition to ads

### ISSUE THREAD

**Issue by MichaelBiermann** [wintermeyer/vutuv#445]
Donations and a fanshop might be an addition to ads.

Mobilegeeks shows what can be done:

https://www.mobilegeeks.de/artikel/leserhilfe/

Especially a fanshop using i.e. spreadshirt.com might work for you:

https://shop.spreadshirt.de/MobileGeeks
https://shop.spreadshirt.es/freesound

I have bought T-shirts of MobileGeeks and freesound.org

![img_20161021_203212](https://cloud.githubusercontent.com/assets/489600/20636341/9685c6a2-b36b-11e6-8479-df0ee7bde70c.jpg)

**Comment by wintermeyer** [comment]
Good idea! I put that on my list. But not for 2016.
