### ISSUE TITLE
Further Attributes

### ISSUE THREAD

**Issue by oliverandrich** [wintermeyer/vutuv#45]
We now have users, with e-mail-addresses, connections and groups. Things that we will need to add in the future are from my point of view:
- addresses incl. geolocation and map links
- phone numbers
- links to social media profiles
- urls like homepage links and so on

Do you agree with that? And what do you think about "company" as another metadata field? Or is is a side effect of an address? 

Depending on your comments I would create new tickets for the individual fields and also write down a spec for the fields based on what Google and so on use for these meta data objects.

**Comment by wintermeyer** [comment]
IMO we don't need the geolocation data in the first step because the user will not be able to enter it any way. Maybe `organization` is better than `company`. It's broader.
