### ISSUE TITLE
Flash messages should be displayed longer

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#456]
### Expected behavior
One should have a chance to read the flash message without a problem. We should double the time it displays. The time should be a configuration variable.

### Actual behavior
It gets displayed and hides away super fast.

**Comment by cjfreeze** [comment]
It's doubled... though considering the value is set in the CSS, I would say that making it a config option is more effort than it's worth. You can just change the number in `main.css`. For future reference, that is (currently) line 364, the `animation` tag that belongs to `.message p`. The value that you want to change is `<num>s forwards`  replacing `<num>` with the duration in seconds. It is currently 6 seconds.
