### ISSUE TITLE
Fix the correct display of "Follow" button.

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#46]
The commit https://github.com/vutuv/vutuv/commit/97c711774097bab7919fce6551dc41ee46b51c9c falls short because the number of followers and followees is limited to 5 in user#show:

```
def show(conn, %{"id" => id}) do
  user =
    Repo.get!(User, id)
    |> Repo.preload([:groups, :emails,
                    followee_connections:
                      {Connection.latest(5), [:followee]},
                    follower_connections:
                      {Connection.latest(5), [:follower]}])
```

I don't know if it is better the just fetch all data from the SQL database and don't limit it or to do a second request to the database to just get the status for this one connection. I guess the later way would be the more secure one in case a user has many hundert thousand of connections.

**Comment by cjfreeze** [comment]
I changed the following

```
followers_count = Repo.one(from c in Connection, where: c.follower_id == ^user.id, select: count("*"))
followees_count = Repo.one(from c in Connection, where: c.followee_id == ^user.id, select: `count("*"))
```

to the following

```
followees_count = Repo.one(from c in Connection, where: c.follower_id == ^user.id, select: count("followee_id"))
followers_count = Repo.one(from c in Connection, where: c.followee_id == ^user.id, select: count("follower_id"))
```

and then changed the following

```
<%= if Enum.count(@user.followee_connections) > 5 do %>
```

to the following

```
<%= if @followees_count > 5 do %>
```

Now User#show displays the 5 newest followers and displays a link to view the full follower list.

**Comment by wintermeyer** [comment]
The code `unless Enum.any?(@user.follower_connections, fn(x) -> x.follower_id == @current_user.id` doesn't work as expected because only the last 5 `follower_connections` are fetched from the database. In case someone has 1,000 followers and the `current_user` is not in the latest 5 of them than the `unless` delivers the wrong output.

The following controller code only fetches 5 followers and followees:

```
user =
  Repo.get!(User, id)
  |> Repo.preload([:groups, :emails,
                 followee_connections:
                   {Connection.latest(5), [:followee]},
                 follower_connections:
                   {Connection.latest(5), [:follower]}])
```

**Comment by cjfreeze** [comment]
Ah, forgive me for misunderstanding. I was able to reproduce the issue and I am promptly working on it. I think the easiest solution would be to directly query using a helper function. I'll work on implementing it.

**Comment by cjfreeze** [comment]
Issue solved.
