### ISSUE TITLE
Normalizing Skill values

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#463]
### Expected behavior
It shouldn't matter if somebody enters `Javascript`, `javascript` or `JavaScript`. The system should always save it as `JavaScript`. There are many of those examples. We wouldn't like to have `php` as a skill but `PHP`. 

### Actual behavior
The system saves all the skills as they are entered by the user.

# Solution
We need a resource `skill_name` with the field `value` which has to be not nil and unique.
Than we need a resource `skill_synonym` which belongs to `skill_name` and has the field `value`. That field is stored lowercase only. 

Only admins have access to both resources. They can use plain Phoenix scaffolding.

When a new skill is created the validation function has to run it first lowercased through `skill_synonym`. If it finds one it has to replace self to the `skill_name` `value`.

**Comment by cjfreeze** [comment]
I'm trying to think of border cases that could cause duplicate skills

I'm thinking that the synonym needs to be free of all whitespace and punctuation

S.Q.L. will reduce to sql, Node JS and Node.js will both reduce to nodejs
