### ISSUE TITLE
Sort the result of a search for a skill

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#464]
### Expected behavior
When I search for `PHP` I want the top PHP guys. The once with the highest upvote rating. But I don't want the ones which have high upvote ratings which haven't changed the last 12 months.

This needs to be discussed.

Some ideas:
http://sorentwo.com/2013/12/30/let-postgres-do-the-work.html

**Comment by ThraaxSession** [comment]
If you do it with postgres, there is hardly/no chance to use another DB. Therefore you made vutuv open source, it should be possible to use vutuv with other DB systems too. But it would be possible to use a decentralized vutuv network with one clear structure (synchronized DB back ends, kinda like cluster network). I think it's better to sort on the code side as on DB level. And later it is still possible to create a scaling, decentralized network. :)

**Comment by wintermeyer** [comment]
I would never solve this in the database. The link is just for information about a possible way to solve it. Just to get an idea.

**Comment by ThraaxSession** [comment]
Ok :D it was just confusing
