### ISSUE TITLE
Login link from email takes me to "Page not found"

### ISSUE THREAD

**Issue by rendro** [wintermeyer/vutuv#465]
### Expected behavior
When I click on the authentication link in the email I would expect to be logged in, able to do something.

### Actual behavior
Login link takes me to "Page not found"

### Steps to reproduce the behavior
Login as me 🐙

**Comment by wintermeyer** [comment]
Please try again and provide us with the exact time (including the second and the time zone) the error happens. Providing your name or email address would help too. Than we can look it up in the log file to narrow down the error. Thank you for your help!

**Comment by rendro** [comment]
Tried to log in 11/30/2016 @ 9.59am (PST)
Name: Robert Fleischmann
Email: rendro87@gmail.com

https://www.vutuv.de/users/robert.fleischmann.rendro87atgmail.com

**Comment by wintermeyer** [comment]
I can't find anything in the logs. Please delete the browser cache, try it again and add the time to this issue.

**Comment by rendro** [comment]
Tried different browsers.
Recent attempt: Firefox (49.0.2)  `12/2/2016 12:01 PM (PST)`

Can not access my profile. Can access the search though. If I search for myself and click on my profile, same error. Can access other profiles.

Would love to delete my account by now, but since I can not access it there is no way to delete it.

![screen shot 2016-12-02 at 12 07 55 pm](https://cloud.githubusercontent.com/assets/422168/20848679/fecad010-b887-11e6-8fba-871f7a7f2288.png)

**Comment by cjfreeze** [comment]
@rendro We're really sorry that it took this long to fix this issue, but you should be able to log in now. Can you let us know if this is the case?

**Comment by rendro** [comment]
Thanks for fixing this! I can verify that logging in works
