### ISSUE TITLE
Vutuv misses suggestion function

### ISSUE THREAD

**Issue by Elmi77** [wintermeyer/vutuv#467]
In Vutuv it is currently only possible to find people one already knows. For a business network this is not enough, here it is more interesting to get people suggested, that work in the same business.

So a suggestion function would be nice which shows people that fit to the own profile and where one could follow and get in touch with.

**Comment by ThraaxSession** [comment]
See #430

**Comment by wintermeyer** [comment]
I'm closing this issue because of #430. We are aware of the problem. But I appreciate the input! Thank you.
