### ISSUE TITLE
Left align email addresses

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#477]
### Expected behavior
The email addresses card should look nicer.

### Actual behavior
![bildschirmfoto 2016-12-01 um 16 47 12](https://cloud.githubusercontent.com/assets/69770/20800487/f82a7eba-b7e5-11e6-8508-9e603e408c61.png)

**Comment by xamiam** [comment]
How about:

SCSS:
dl {
  margin: 15px 0;
  dt,
  dd {
    padding: 0;
    margin: 10px 0;
    min-height: 0;
    display: block;
  }
  dt {
    margin: 15px 0;
  }
}
