### ISSUE TITLE
Display small avatars for followers and followees

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#48]
Add a little version of the avatar in a new first `<td>` column. So that the user can recognize someone faster by the photo.

![bildschirmfoto 2016-06-24 um 09 47 31](https://cloud.githubusercontent.com/assets/69770/16331439/c88e08a2-39f0-11e6-8fa6-82a1b989aed6.png)

**Comment by cjfreeze** [comment]
Note that I did this without touching the css, so this solution will need to be updated when it comes time to focus on css.
