### ISSUE TITLE
Buggy route for admin/skills/...

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#482]
### Actual behavior
http://localhost:4000/admin/skills/ruby%20on%20rails doesn't work:

![bildschirmfoto 2016-12-04 um 09 18 25](https://cloud.githubusercontent.com/assets/69770/20864903/eb36ceba-ba02-11e6-8421-a3ff1bc36477.png)

**Comment by cjfreeze** [comment]
This has to do with the slugs for skills currently allowing spaces. This is one of the things that will be fixed in the upcoming slug changes. I'll close this issue with the others when the changes are pushed.
