### ISSUE TITLE
OCR photos of business cards and connect to their owner

### ISSUE THREAD

**Issue by steely-glint** [wintermeyer/vutuv#496]
Feature request:
Add facility to import (and scan?) photos of business cards.
This would be super useful when visiting a conference or exhibition.

-There used to be a linked-in sevice like this called CardMunch - it was a mechanical turk design
with humans doing the transcriptions - but now I suspect webrtc etc would support it

**Comment by BrummbQ** [comment]
Actually this feature may not be that hard to implement. I've just run some manual tests with the cognitive services api (https://www.microsoft.com/cognitive-services/en-us/computer-vision-api) and the ocr results were not that bad.

I will try to sketch up a prototype. Can you maybe provide some example photos and expected results?

**Comment by wintermeyer** [comment]
I understand how we can use the MS API for doing the actual OCR part. But I'm not sure if we can solve the WebGUI part with out JavaScript. Can we?

**Comment by BrummbQ** [comment]
I don't understand that part. Why do we need Webrtc/JS? Just take a photo with your phone, visit vutuv and upload the image with a plain old post formular. Then we can try to import the contact on the server or add them to his contact list, if we can detect any name or mail.

It may be hard to extract all information from the business card, but just linking 2 people together should be quite possible.

**Comment by wintermeyer** [comment]
I find the workflow cumbersome. You have to take a photo. Than you have to upload that photo with the browser. Than you have to check if the OCR process made any mistakes. But I'm all in for the idea. I'm just not sure if this is become an often used feature.

**Comment by BrummbQ** [comment]
Yeah, I'm not sure about that too. Though the upload part is even easier. You can take and upload a photo directly from the browser, I tried it with the vutuv avatar upload.

Anyway, I had some success on the ocr part (implementation https://github.com/BrummbQ/cognixir-demo/commit/d11e4dae51b14b69df8559a820b59b113dd433a2). The reader extracts information snippets from the card like name, phone, mail or website. Some sample output:

Reading card 8
Potential name or title: TRAVIS HOWELL
Potential phone number: 123 456 7890
Potential email: trvshowell@gmail.com
Potential website: www.TravisHD.com

Reading card 9
Potential name or title: CHRIS SPOONER

Reading card 10

Reading card 11
Potential name or title: David Elfstrom
Potential email: david@elfstromengineerinq.com
Potential website: www.elfstromengineerinq.com

**Comment by wintermeyer** [comment]
Very promising! 

## Open questions:

- How to pay for it? vutuv is a free service and I don't want to start to charge users for using this feature. I might be willing to try it and see how many people are using it anyway.
- Where to put it on the website? That's a tough one. We do not have a navigation bar menu (for good reasons).
- What do we do with additional data? Lets assume someone has just his/her name and email address in vutuv and now somebody else scans the business card and we therefor now the phone number. We can't just add it without asking the owner. So just forget it?
- How to handle outage of the API? Do we store the scans and queue the OCR process or how do we handle it? Depending on that we have to take care of a potential outage.

**Comment by BrummbQ** [comment]
### Pricing
We can get 5000 calls each month for free. After that we need to disable the service. Or pay $1.50 per 1000 additional calls. Dunno about financing, maybe ads or sponsors.

### UI
The logical place would be the search/add contact site. We could place a small box in the side bar.

### Data
Just extract the needed information and drop the rest. When 2 users are linked together, the process is done. As an extra, if the owner of the business card has no vutuv account, maybe we could send an invitation mail. That would give you also a new "recruiting channel"

### Queuing
Sounds to me like an ops issue. For the start, I think a error message would suffice, if the api went down. Or build a queuing system with rabbitmq or something. But thats a lot of work
