### ISSUE TITLE
Links should open up in new tabs/windows.

### ISSUE THREAD

**Issue by ghost** [wintermeyer/vutuv#498]
### Expected behavior

A click on a link leading outside of vutuv should always open a new tab or windows. (target=_blank)

### Actual behavior

Clicking on a link in Link section for example, causes switching to the linked page and user maybe confused.

A possible solution would be a configuration setting that each user could set to his/her favourite behaviour.

**Comment by wintermeyer** [comment]
I hear you but I am not a big fan of `target=_blank`. But let's do a voting for this.

@all: Please use https://twitter.com/VUTUV/status/807529014114000897 or the reaction functionality of Github.

**Comment by oliverandrich** [comment]
This is by no means a feature or an expected behavior. Sorry, I want to be in control what my browser does.

**Comment by wintermeyer** [comment]
The result of the Twitter vote:
![bildschirmfoto 2016-12-19 um 13 41 43](https://cloud.githubusercontent.com/assets/69770/21313238/f35d02ae-c5f0-11e6-8b4f-098db9e2f8bf.png)

I guess we have to add a configuration option that allows that. I'm not agreeing with it but I can live with a configuration option for this behaviour.
