### ISSUE TITLE
Emails are send unecrypted

### ISSUE THREAD

**Issue by flat235** [wintermeyer/vutuv#502]
### Expected behavior
Emails should be send over encrypted (tls) connection.
### Actual behavior
Emails are being send over unecrypted connection.
#### Screenshot from GMail:
![screenshot_vutuv_2](https://cloud.githubusercontent.com/assets/3152820/21272331/102bb3d2-c3bf-11e6-8360-b4a8bbf719dd.png)
### Steps to reproduce the behavior
Request Sign-In email.

**Comment by wintermeyer** [comment]
Thanks for bringing that up! This is currently not in our hand. We are using a SMTP gateway and have little control over it. I will keep your input in mind. We could run our own SMTP gateway but honestly I would prefer to put the work which needs to be done to make that happen into other features of vutuv.

Botton-Line: I'm closing this issue for now and I can not tell you when we are going to provide this.
