### ISSUE TITLE
Add validation for email uniqueness

### ISSUE THREAD

**Issue by cjfreeze** [wintermeyer/vutuv#51]
Currently two users can have the same email.

**Comment by wintermeyer** [comment]
An email should only exist once in the system. So we have to add a validation which checks for uniqueness during create and update of a record.

**Comment by cjfreeze** [comment]
This feature was a surprising mess. As part of this commit, I was forced to comment out these parts of user#create.

```
    #groups =
    #  for name <- ["Friends and Family", "Business acquaintances"] do
    #    Group.changeset(%Group{}, %{name: name})
    #  end

    changeset =
      User.changeset(%User{}, user_params)
    #  |> Ecto.Changeset.put_assoc(:groups, groups)
```

For some unknown reason, when put_assoc is called on the changeset and unique_constrant in the email model is tripped, it caused insert to raise. Individually they work fine. Together they break. No one in #elixir-lang was able to determine why either.

**Comment by cjfreeze** [comment]
Jose confirmed it, it's an Ecto bug.
