### ISSUE TITLE
Editing e-mail address and web links deletes them

### ISSUE THREAD

**Issue by oliverandrich** [wintermeyer/vutuv#522]
I consider this a show stopper. If I try to edit a link or email address it is deleted from my profile. I verified it twice, that I click the correct icon. May be you can also consider to use bigger icons?

**Comment by wintermeyer** [comment]
AFAIK this is a CSS problem. You're right. It's a big problem.

**Comment by xamiam** [comment]
This is the bug:

![bildschirmfoto 2017-01-17 um 21 29 24](https://cloud.githubusercontent.com/assets/309421/22038579/0d306e74-dcfc-11e6-94ad-aae73fa2dd0e.PNG)

What's that for, anyway?
