### ISSUE TITLE
PIN system to delete a Free Basics account

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#523]
### Expected behavior

A Free Basics user should get a PIN when he wants to delete his vutuv account.

### Actual behavior

He gets a magic link which is no good for him.

**Comment by cjfreeze** [comment]
I just tested this. When I have the header `X-IORG-FBS = true` I receive a pin. Are free basics users reporting differently?

**Comment by wintermeyer** [comment]
hmmmm... maybe the de translation is wrong. I'll check it tomorrow.
