### ISSUE TITLE
Fix URLs

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#525]
Please visit https://www.vutuv.de/users/florian.marquardt and click on the links to see the bug.

![bildschirmfoto 2017-01-16 um 13 34 46](https://cloud.githubusercontent.com/assets/69770/21983242/96e12d82-dbf0-11e6-8e2a-b39c295110ea.png)

A click on the first link leads to this (have a look at the URL of the browser):

![bildschirmfoto 2017-01-16 um 13 35 34](https://cloud.githubusercontent.com/assets/69770/21983266/b09501e0-dbf0-11e6-828b-454cc002836c.png)

We might have to write a migration for this to fix already existing wrong URLs in the system.

**Comment by cjfreeze** [comment]
I have tested this and while I am unsure how he managed to create a link that was not prefixed by `http://` I have determined the way to fix it is indeed a migration.
