### ISSUE TITLE
Search for "icinga" shows "icinga 2", but following the link shows "Fehler"

### ISSUE THREAD

**Issue by tk-wfischer** [wintermeyer/vutuv#529]
### Expected behavior
When searching for a name, the presented links in the results should work.

### Actual behavior
In my case I have searched for "icinga" and a list of tags has been returned. The list contains "icinga" and "icinga 2":
![search-icinga](https://cloud.githubusercontent.com/assets/10231856/22509493/88cc19c8-e88e-11e6-81c6-8e0c6e8e4303.png)

When I click on "icinga 2" I get:
![follow-tag-icinga-2](https://cloud.githubusercontent.com/assets/10231856/22509503/8f7273d0-e88e-11e6-91a3-6899e0dbcc67.png)

### Steps to reproduce the behavior

1. At https://www.vutuv.de/search_queries/new enter "icinga"
2. Click on "icinga 2"

**Comment by wintermeyer** [comment]
@tk-wfischer Thanks for the bug report!
