### ISSUE TITLE
Exports Card is suppressed by footer

### ISSUE THREAD

**Issue by verymilan** [wintermeyer/vutuv#537]
The "Exports" box is suppressed by the footer.
I am using Chromium with the default zoomlevel on a 1920x1200 screen.

![2017-02-27-134316_1920x1200_scrot](https://cloud.githubusercontent.com/assets/10698140/23361962/ac6b8a3e-fcf3-11e6-82d6-324d61fa1301.png)

(Sorry cannot fork and create a pr atm)

**Comment by wintermeyer** [comment]
That's an annoying but known bug. It's going to be fixed next week. The CSS is already in https://github.com/vutuv/vutuv/pull/535

**Comment by verymilan** [comment]
Oh i see. :)
