### ISSUE TITLE
Personal verification

### ISSUE THREAD

**Issue by ddeimeke** [wintermeyer/vutuv#545]
To ease the process of verifying user accounts, adding a "contact state" would be great.

It could be one of these:
- Met this contact personally
- Had video conferences / phone calls with this contact
- Know this contact from internet conversations
- None of those

This could help an automated "verifyer" to decide the verification.

Maybe a look at the "web of trust" know by pgp/gpg would be an option.

**Comment by wintermeyer** [comment]
This is a very complex issue. I'll close it for now because we have bigger fish to fry. I'll keep it on my mental to-do-list.
