### ISSUE TITLE
private mode for birthday

### ISSUE THREAD

**Issue by schtobia** [wintermeyer/vutuv#547]
### Expected behavior
As a logged in user, I want to be able to set the birthday to private. I want to set it correctly (for my birthday e-mail), but i don't want to share it with the world.

### Actual behavior
Every birthday is public.

### Steps to reproduce the behavior
Set the birthday to a value other than 1900-01-01.

**Comment by ghost** [comment]
I think the scope of this is greater than just birthdays.

**Comment by schtobia** [comment]
Not exactly, as the birthday is marked specially, for the birthday e-mail, so there *are* actually use cases for a "present but hidden" datum.

But of course, [this resolution](https://github.com/vutuv/vutuv/issues/548#issuecomment-286613442) is much more important.

**Comment by ghost** [comment]
Sorry I should have been more specific. 

I was talking about introducing privacy logic as a whole vs doing it for just one attribute. 

I think think there is a need to introduce a way to specify what content you will allow to be public but I think more thought beyond just the birthdate will be required for that.

**Comment by wintermeyer** [comment]
The scope is bigger than birthday. I want to tackle this in 2.0. So that the visibility of all information can be configured.
