### ISSUE TITLE
Deletion of birthday

### ISSUE THREAD

**Issue by schtobia** [wintermeyer/vutuv#548]
### Expected behavior
As a logged in user, I want to easily delete my birthday. Setting it to 1900-01-01 does the job, but this is not intuitive.

### Actual behavior
I have to set it to 1900-01-01 to hide it.

### Steps to reproduce the behavior
Set the birthday, then try to delete it.

**Comment by ghost** [comment]
I think we should turn the birthday field into a plan text input. That will facilitate the ability to empty out the content.

**Comment by ghost** [comment]
If I were to add this functionality what would be the preferred format of the string?

`DD/MM/YYYY` ?

**Comment by schtobia** [comment]
IMHO there are three popular ways of entering:

 * `YYYY-MM-DD`
 * `MM/DD/YYYY`
 * `DD. MM. YYYY`

But I wouldn't check specifically against these three. Just feeding it to [Date.parse](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) should be extensive enough.

**Comment by ddeimeke** [comment]
If I had the choice, I would vote for ISO, which is YYYY-MM-DD.

**Comment by wintermeyer** [comment]
To make life more complicated: Some people just want to enter the day and month but not the year and some just want to enter the year. This birthday thing is very delicate.
