### ISSUE TITLE
Editing my profile is broken

### ISSUE THREAD

**Issue by ursjoss** [wintermeyer/vutuv#553]
Clicking on the edit icon next to my name (https://www.vutuv.de/users/urs.joss/edit) results in an exception

<pre>
Fehler! Irgendwas stimmt hier nicht. Wir würden uns über einen Bugreport unter freuen.
</pre>

I tried it several times, once at roughly 2017-11-28 19.45.01.

### Expected behavior

I can edit my profile

### Actual behavior

Exception is thrown.

### Steps to reproduce the behavior

Click the edit button.

**Comment by wintermeyer** [comment]
Thank you very much for this bug report! I'll fix it right away.

**Comment by wintermeyer** [comment]
The new version is online. Thanks again for the bug report.

**Comment by ursjoss** [comment]
Thanks, Stefan
