### ISSUE TITLE
discrepancies in documentation about latest versions

### ISSUE THREAD

**Issue by zenny** [wintermeyer/vutuv#556]
Hi,

Great project, great principles.

The documentation asks to install latest versions of Erlang/Elixir. As of this writing the stable versions are 20.x and 1.6.x respectively.

'mix deps.get' generates errors as v1.5.2 was hard-coded in mix.exs and other plugs. 

Besides, specified versions of two modules, namely hackney and quantum reportely deprecated while running 'mix deps.get'.

Cheers,
/z

**Comment by wintermeyer** [comment]
Fixed.
