### ISSUE TITLE
New Sign Up Page

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#558]
# Introduction

vutuv is a business network. Think of it as a free, fast and secure open-source alternative to [LinkedIn](https://www.linkedin.com) or [XING](https://www.xing.com). Please feel free to add comments and questions (as comments) to this issue.

# The Task

**Create a mockup sign up HTML page.** English or German (language doesn't matter for this mockup). To solve this issue no Elixir code has to be written. Just plain old HTML and CSS (probably embedded in the HTML). If you need data use dummy data. Please store the file(s) in `misc/mockups/` or a subdirectory of it. The HTML file should contain the form. Later on someone will convert this mockup into a Phoenix template. But that will be a separate issue. The old version of this sign up page is attached to this issue in a comment.

Please create a pull request to submit your work (master branch).

# General Thoughts about the Sign Up Screen

If you visit https://www.vutuv.de without being logged in this is your first page. I still like the idea and the feeling of the old one (in the first comment you'll find a gz of it). It would be nice to keep the idea but we don't have to.

<img width="1228" alt="The old login screen." src="https://user-images.githubusercontent.com/69770/53193838-4b2c0c80-3612-11e9-8a4d-afb4bd9e431b.png">

**The sign up screen is the first vutuv page new users see.** It has to be positive and welcoming. If we can exchange the image during the day or the month it would be nice. But that is not a necessity. 

## WebPerformance

Speed is paramount. Our payload budget for HTML, CSS, the SVG embedded vutuv logo and JavaScript (if needed) for this page is 14 KB (gzip compressed). We load one image (the background image) which is not included in the 14 KB.

### JavaScript

I think we don't need JavaScript on the sign up page. But I'm open for it in case it gives us big benefits.

### Font

Only use system fonts. No fonts which have to be loaded.

### The Background Image

The image should be taken by one of us or from a free source (e.g. [unsplash](https://unsplash.com)). The credit information should be shown somewhere on the page.

The image should be not bigger than 28 KB. If we absolutely must have a bigger image the worst case limit for that image is 47 KB. But there has to be a good reason for that.

Obviously it is not easy to find good full page images which can get compressed to 28 KB or 47 KB. If it was easy anybody could do it.

### Logo

This should be an inlined vector image.

### Misc

All other buttons or graphics probably should be inlined vectors too. But I'm open for better ideas if available.
 
## Navigation

Can be a classic top navigation or something else. It has to have these two elements: 

- A login link
- A search link

But obviously those elements can be at a different location on this page in case somebody has a better idea. 

## Sign Up Form Elements

In the old version I thought it would be a good to have a field where new users enter `tags`. What seemed to be a good idea at the time confused non-technical users. So for the new version I propose the following elements:
 
- Gender/Sex (a pull down field or radio button with male/female/diverse)
- first_name
- last_name
- email_address
- password
- submit button

No privacy settings. That can be done later. Keep it simple.

## Footer

We need a place to link to the imprint and some legal stuff. So some sort of footer would be nice.

# CSS Frameworks

It would be great to use a CSS framework like [Bootstrap](https://getbootstrap.com) but we don't have to. Especially for this sign up page we can do without. Never the less using a CSS framework would make stuff on boarding easier for any new developer.

# Responsiveness

Of course it has to be responsive. It should look nice on a mobile phone (portrait mode), an iPad like devise (landscape mode) and on a desktop. The old version was kind of ok but couldn't win a beauty contest. The new one should look nicer on a mobile devise.

<img width="346" alt="The old sign up screen on a mobile devise." src="https://user-images.githubusercontent.com/69770/53199074-64d35100-361e-11e9-9c1d-b4b08c835fe3.png">

# Browser

No need to waste time on old legacy browsers. The page has to work on the newest versions of the following browsers:

- Safari
- Chrome
- Firefox

# Accessibility

a11y is key. We need to have a solid solution for this. The v2 version has to be accessible with w3m. The v1 wasn't (e.g. the form fields don't show any name):

<img width="682" alt="bildschirmfoto 2019-02-26 um 09 08 03" src="https://user-images.githubusercontent.com/69770/53396987-2fc05900-39a6-11e9-87b5-cc15b35136c9.png">

# Misc

- I'm thinking about publishing the current number of users on this page. That would be cool. But it has to look nice.
- http://bradfrost.com/blog/post/dont-get-clever-with-login-forms/

**Comment by wintermeyer** [comment]
Here's the old sign up page:

[vutuv-v1-sign-up.zip](https://github.com/vutuv/vutuv/files/2891069/vutuv-v1-sign-up.zip)

**Comment by MarioRicalde** [comment]
Hello. I hear you need some front-end help and perhaps some design?!

I have some questions:

1. Above you mention that you're considering having the CSS in-line, or it's me misunderstanding.
2. Are there any design guidelines? I'd like to work on this first on [Figma](https://figma.com/) and move from there.

If you need any other design work done, count me in. I'm down to do it all!

**Comment by wintermeyer** [comment]
@MarioRicalde Good to see you. But it's your birthday. Go out and celebrate! ;-) 🎂

> 1. Above you mention that you're considering having the CSS in-line, or it's me misunderstanding.

The current plan is indeed to inline the CSS. If we manage to get everything within the 14 KB (compressed) this would be the fasted way web performance wise.

> 2. Are there any design guidelines?

No. Not yet.

> I'd like to work on this first on [Figma](https://figma.com/) and move from there.

Please go ahead with Figma. I have never worked with Figma but saw you praised it in Twitter.

> If you need any other design work done, count me in. I'm down to do it all!

:-)

**Comment by MarioRicalde** [comment]
@wintermeyer I'll try ;) it's still the weekend.

More questions:

Do you have any guidelines for the design?
Any colors I have to stick to?

If we don't have any of the above I can work on getting that going too. 

Cheers.

**Comment by wintermeyer** [comment]
> Do you have any guidelines for the design?

No. We create a v2.0 on a green field. Have a look at https://www.vutuv.de to see the old version.

> Any colors I have to stick to?

Nope.

**Comment by MarioRicalde** [comment]
Nothing like a white canvas to excite me.

**Comment by MarioRicalde** [comment]
I'll take a stab on it ASAP.

**Comment by MarioRicalde** [comment]
@wintermeyer You can see progress live as I go here:

https://www.figma.com/file/NnysAwaxD0k01e90V9OPq4Tb/Vutuv?node-id=0%3A1

**Comment by MarioRicalde** [comment]
I think we might need a separate issue to discuss some things related to general branding and message; however, for the time being, I'm going to keep the conversation here to avoid having to pollute the issues without your consent.

I'm currently re-imagining what the signup/login page should look like. Since it's intended to be used as some sort of wall for users to do an action (login or signup), I'm focusing on explaining what vutuv is. I'd currently like to have 3 to 4 core 'features' or reasons to create an account and join. I'm also adding some extra columns.

I've also rearranged the order of the inputs, to leave personal information for last. Gender is the last one.

Still a very rough draft, but it's some progress. Colors are not final. Etc.

Update, attaching image preview.

![image](https://user-images.githubusercontent.com/125900/53691478-9ea20700-3d44-11e9-8a8f-d799b7794b4b.png)

**Comment by wintermeyer** [comment]
> I think we might need a separate issue

Please do fire up new issues as needed.

> I'm currently re-imagining what the signup/login page should look like. Since it's intended to be used as some sort of wall for users to do an action (login or signup), I'm focusing on explaining what vutuv is. I'd currently like to have 3 to 4 core 'features' or reasons to create an account and join. I'm also adding some extra columns.

We don't need to list 3-4 core features here. "Fast and secure business network" is plenty. People sign up because they are curious. And they are already on the page. So no need for more text here.

I like the different counters.

> I've also rearranged the order of the inputs, to leave personal information for last. Gender is the last one.

I see. BTW: We don't need a "Keep me logged in." checkbox here.

> Still a very rough draft, but it's some progress. Colors are not final. Etc.

Are you doing a background image or is this approach one without a background image?

@xamiam Please jump in in case we are missing anything.

**Comment by MarioRicalde** [comment]
Re core features, I’m basically trying to interest people and offer ways to
explore or showcase what they can do. Twitter m, Facebook and other
networks do something similar. It you disagree heavily we can go without
it, but i really think it’s a good thing to have.

I’m trying and approach without an image and with a vector art down the
road to focus on performance. My approach with the branding is to stay with
“classy and out of the way, content is king”.

Also what do you think of the pronunciation?  Not sure if that’s the
correct one.

**Comment by wintermeyer** [comment]
> Re core features, I’m basically trying to interest people and offer ways to explore or showcase what they can do. Twitter m, Facebook and other networks do something similar. It you disagree heavily we can go without it, but i really think it’s a good thing to have.

Let's do two versions. One with the bullet points and one without. Then we'll do an a/b test.

> Also what do you think of the pronunciation? Not sure if that’s the correct one.

It starts with a v like in Venice.

**Comment by wintermeyer** [comment]
This red feels a bit aggressive/bloody doesn't it?

<img width="697" alt="bildschirmfoto 2019-03-03 um 09 17 37" src="https://user-images.githubusercontent.com/69770/53692732-32032880-3d95-11e9-91a9-08a188407773.png">

**Comment by MarioRicalde** [comment]
I’m aiming to make it more of an accent color that is not really red will
see what I can do there.

**Comment by wintermeyer** [comment]
BTW: The gender field can be a drop down select field or a radio button. male/female/other

**Comment by MarioRicalde** [comment]
I'm working on changes right now. Feel free to jump in and see why I love
Figma so much with the link above. Just click on my icon top right.

Cheers!;

**Comment by MarioRicalde** [comment]
@wintermeyer 
![image](https://user-images.githubusercontent.com/125900/53695304-5eac4580-3d7f-11e9-890b-132206ba43f0.png)

What about these checkboxes and texts, do we intend to keep them?

**Comment by MarioRicalde** [comment]
![image](https://user-images.githubusercontent.com/125900/53695496-032f8700-3d82-11e9-8c2e-f4b875157b73.png)

Progress.

**Comment by MarioRicalde** [comment]
![image](https://user-images.githubusercontent.com/125900/53695924-155ff400-3d87-11e9-9c9a-1fc625456268.png)

Still adding more things, will continue later today. Please provide feedback and assistance with the comments above.

**Comment by wintermeyer** [comment]
> ![image](https://user-images.githubusercontent.com/125900/53695304-5eac4580-3d7f-11e9-890b-132206ba43f0.png)
> What about these checkboxes and texts, do we intend to keep them?

No, we don't need them. We need something like "We do store your data in our database and we do use cookies." (10-15 words) somewhere around the submit button.

**Comment by MarioRicalde** [comment]
Roger that, I will take a stab at it when I wake up.

**Comment by wintermeyer** [comment]
> ![image](https://user-images.githubusercontent.com/125900/53695924-155ff400-3d87-11e9-9c9a-1fc625456268.png)
> 
> Still adding more things, will continue later today. Please provide feedback and assistance with the comments above.

I like it. I'm not sure about the replacement of the bullet points. On the one side I think "less is more" and on the other side I think "nice". Not sure about them.

**Comment by wintermeyer** [comment]
@MarioRicalde 

- I do we translate this idea to the mobile devise?
- I like the idea of the big "VU" in the background. I wonder if the contrast of the "Keep track of those subjects ..." to the background is big enough for people who have less good eyesight.

**Comment by MarioRicalde** [comment]
![vutuv-animation](https://user-images.githubusercontent.com/125900/53881270-df19b300-3fd8-11e9-81d0-b6308ad49c0a.gif)

@wintermeyer thisis what I have in mind so far, something appealing enough, hopefully not too distracting. The idea is that this is a "slide down" kind of panel.

**Comment by MarioRicalde** [comment]
![login - mobile](https://user-images.githubusercontent.com/125900/53882839-007c9e00-3fdd-11e9-8472-d630935d49da.png)

Something like this for mobile @wintermeyer

**Comment by wintermeyer** [comment]
@MarioRicalde About the mobile version: This would be a sign up page. But we'd need a link to a login page on this page. Does this call for a hamburger menu on top or a text link on the page?

**Comment by wintermeyer** [comment]
> ![vutuv-animation](https://user-images.githubusercontent.com/125900/53881270-df19b300-3fd8-11e9-81d0-b6308ad49c0a.gif)
> 
> @wintermeyer thisis what I have in mind so far, something appealing enough, hopefully not too distracting. The idea is that this is a "slide down" kind of panel.

Can the moving background be done with CSS only? No JavaScript?

**Comment by wintermeyer** [comment]
@xamiam Please do your CSS magic for this. But please don't spend too much time on the moving background. We can add that later.

**Comment by xamiam** [comment]
Okidoki.

**Comment by MarioRicalde** [comment]
The animation should be doable exclusively with CSS.

Regarding the login link, that's a copy issue. Right next or underneath the button the text should say. "Already a memeber? Login here."

@wintermeyer the asset sharing for implementing would be much simpler if we had a Figma Team for Vutuv.

Cheers.

**Comment by xamiam** [comment]
Hi there, thank you very much for the great work so far!

I built a PHP-/HTML-Mockup of @MarioRicalde 's Design for performance testing:

https://max-interactive.rocks/vutuv-2/

Here's two versions for performance testing:

Splash Screen without circles: https://max-interactive.rocks/vutuv-2/splash-1.php
Splash Screen with circles: https://max-interactive.rocks/vutuv-2/splash-2.php

SVG and CSS are all inlined, therefore only 1 server request. I am using bootstrap v4 - but only a couple of modules to minimize the css payload.

It makes sense to me to use standard bootstrap elements for the other pages - individually styled, of course. The main benefit of bootstrap is tested cross browser compatibility and detailed documentation - which is helpful for every level of frondend design experience.
@MarioRicalde please feel free to design other screens without restrictions. I am sure we can combine the standard elements of bootstrap with your designs.

Please let me know if you have any issues with the current html mockups.

yours,

max.

**Comment by wintermeyer** [comment]
> Splash Screen without circles: https://max-interactive.rocks/vutuv-2/splash-1.php
> Splash Screen with circles: https://max-interactive.rocks/vutuv-2/splash-2.php

We are on the right track:
https://www.webpagetest.org/result/190309_63_86237a614ef6956df275e14549e93b55/1/details/#waterfall_view_step1

I have the feeling that we have to save a couple of more bytes. But that's feasible. Below 1s is doable.

> Please let me know if you have any issues with the current html mockups.

<img width="429" alt="Bildschirmfoto 2019-03-09 um 16 05 29" src="https://user-images.githubusercontent.com/69770/54073237-2c21b180-4285-11e9-900d-2f866f6185f0.png">

This part seems a bit off. Is this a problem of the font?

Shouldn't the background v of vutuv be bigger?

**Comment by wintermeyer** [comment]
The mobile version is off too:

![IMG_0984](https://user-images.githubusercontent.com/69770/54073271-72771080-4285-11e9-810d-83019d46486b.png)

![IMG_0985](https://user-images.githubusercontent.com/69770/54073272-786cf180-4285-11e9-9977-715b45c04ce4.png)

**Comment by xamiam** [comment]
Hi @wintermeyer - please clarify the "off" ;)

I made some changes...

**Comment by wintermeyer** [comment]
> Hi @wintermeyer - please clarify the "off" ;)

@MarioRicalde Please help me out on this one. Or am I the only one who thinks it is off a bit?

> I made some changes...

The mobile version is not right were it needs to be. But I have a hard time to tell what is wrong.

![vutuv-mobile](https://user-images.githubusercontent.com/69770/54075307-1b316a00-429e-11e9-84c9-f3d2592214b3.gif)

**Comment by MarioRicalde** [comment]
Good progress, I'm out for the weekend, but here's some notes:

If we're expecting a 1 to 1 conversion, then this is off in multiple places.

![image](https://user-images.githubusercontent.com/125900/54080599-58572580-42b9-11e9-8972-cadc7336681a.png)

Front font sizes to line heights, to colors, to backgrounds.

One key thing is the background is really just a V not the whole vutuv. Also it has a gradient.

Input sizes, font sizes in the area, paddings, buttons. They're not properly set.

![image](https://user-images.githubusercontent.com/125900/54080609-9e13ee00-42b9-11e9-94fd-6b80f1f7dedd.png)

**Comment by xamiam** [comment]
Hi there, I updated the splash page and fixed some of the issues. Please note that font sizes, paddings, margins etc. also depend on the css framework we're using. 
I suggest sticking to the standard declarations of bootstrap for now and unifying the style once we have more pages up and running.

@wintermeyer 

![grafik](https://user-images.githubusercontent.com/309421/54526009-c06ed100-4975-11e9-9d79-d7bc2a7cd24c.png)

**Comment by wintermeyer** [comment]
@xamiam Thanks! Can I ask you for one more iteration?

- "Sign up" and "Join our business network" is duplicated. I think just "Sign up" is enough.
- Please use "We store your data in our database and we use cookies."
- Please use "The Fast and Secure Business Network."
- I don't like that the "SIGN UP" Button and the "Already signed up? Login here." text don't have the same hight. 
- Gender: female, male, other
- We need some links for the about page and the legal information about how we store and use data.

# The mobile version

I like the sign up form but I don't like the head part. I'm I the only one? Compared with the desktop version it is boring. Maybe we should move up the member, articles and connections numbers to the mobile head.

@MarioRicalde and @xamiam : Do you have an other idea for that? Maybe just a bigger version of the logo for the mobile? Or am I wrong and this looks perfectly good? 

<img width="285" alt="Bildschirmfoto 2019-03-18 um 13 05 48" src="https://user-images.githubusercontent.com/69770/54529659-cddd8880-4980-11e9-899d-1ccc150e921a.png">

**Comment by xamiam** [comment]
Hi @wintermeyer,

I updated the layout - please see https://vutuv-layout.herokuapp.com/ for changed details.

**Comment by wintermeyer** [comment]
> I updated the layout - please see https://vutuv-layout.herokuapp.com/ for changed details.

Can you get rid of this in the mobile page? I think it does make little sense to have it below the form:

<img width="352" alt="Bildschirmfoto 2019-03-18 um 14 08 01" src="https://user-images.githubusercontent.com/69770/54532332-d2596f80-4987-11e9-825a-a7e280fb90a7.png">

There is room for improvement for the w3m version which is important for people who use screenreader and probably is important for search engines. Please try `w3m https://vutuv-layout.herokuapp.com` in your terminal (you might have to `brew install w3m` first). Here's the result:

<img width="682" alt="Bildschirmfoto 2019-03-18 um 14 09 35" src="https://user-images.githubusercontent.com/69770/54532430-003eb400-4988-11e9-9f9c-74c1c50951cd.png">

@MarioRicalde Are you cool with the new footer or does that destroy your design idea?

**Comment by riverrun** [comment]
Closing this issue now, as the mockup has been completed, and the sign up page was updated in #637.
