### ISSUE TITLE
API System

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#560]
Since we start version 2.0 on the green field we can use that possibility to create a good JSON API.

Idea:
Third party software should be able to do everything by RESTful JSON API calls. A user can request an API key which gets generated right away and which can be deactivated in case people do any sort of harm.

Questions:

- Do we need a rate limit? How can we implement that?

**Comment by hendri-tobing** [comment]
What are some examples of third party software that will connect through the API?

**Comment by wintermeyer** [comment]
I don't have an example for this. I just think that a proper RESTful API is key for success. Because I think that 3rd party software provider will fill feature gaps we don't foresee today.

**Comment by riverrun** [comment]
The current plan is to have separate api controllers in the `controllers/api` directory and update the existing view files with json rendering information.

In the router, there will be a separate pipeline for json, which will be scoped to `/api/v1`.

**Comment by riverrun** [comment]
Fixed in #639.

Updated directory structure in #641 - the controllers and views are now in the `lib/vutuv_web/api` directory.
