### ISSUE TITLE
Prevent user enumeration - wording of sign up warnings

### ISSUE THREAD

**Issue by hendri-tobing** [wintermeyer/vutuv#567]
![image](https://user-images.githubusercontent.com/11748187/53373471-1f998100-3988-11e9-9995-81082676e589.png)

Protect users email from hacker, by changing the word email "has already been taken", to something like: "Please check your email to complete the registration".
The email sent to the mailbox is something like:
"You tried to sign up, but you already have an account! Please use the following link to sign in..."

For failed sign in, because the email is not exist:
![image](https://user-images.githubusercontent.com/11748187/53374285-7e5ffa00-398a-11e9-8388-d899009add0d.png)
We can change it to "We have sent an email!"
At the mailbox, we send something like:
"Someone, maybe you, tried to use this email to sign in to vutuv.com, but this email address doesn't have an account! You might have signed up using a different email address or please sign up on vutuv.com."

So the hacker have no idea which emails are registered or not. 

Because users email are the core component in vutuv, we have to protect them. Maybe we could also disable user with lower privilege (or event for all users) to view other users email. We can change the way of the communication by using internal messaging service. This is just an idea.

**Comment by riverrun** [comment]
Links to information about adding user enumeration protection to the registration process:

http://davecallan.com/web-security-account-enumeration-prevention/
https://portswigger.net/blog/preventing-username-enumeration
https://security.stackexchange.com/questions/69370/preventing-user-enumeration-on-registration-page

## Proposed changes to the registration process

If there is an error with registration, check the errors to see if the email has already been taken. If the email has been taken, send an email to the user with a message saying that they are already registered. If there is a different error, render the new user page again with the error.
