### ISSUE TITLE
Url/Link create doesn't generate a screenshot

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#569]
On https://www.vutuv.de/users/stefan.wintermeyer/links I do the following:

![create-url](https://user-images.githubusercontent.com/69770/53440780-9f196580-3a05-11e9-9fe0-fab0a0aac390.gif)

The screenshot generator doesn't work.

I have no idea why but I think it is our code and not the Browserstack API.

Just in case here are the info for the Browserstack-API:
https://www.browserstack.com/screenshots/api

**Comment by hendri-tobing** [comment]
I have checked this bug. It seems Browserstack API is OK.

The problems are:
1. The code does not insert/update the database (url.screenshot)
2. Somehow it also does not copy the screenshot file to the correct image folder from temporary upload directory
3. Since the logic on card_list.html.eex cannot find the url.screenshot on the database, it shows the default "/images/screenshot.png"

I will update the progress soon.

**Comment by wintermeyer** [comment]
I tried to replay it in the console and got stuck here:

    iex(21)> url |> Url.changeset(%{screenshot: upload}) |> Repo.update
    12:47:06.927 [error] Task #PID<0.551.0> started from #PID<0.448.0> terminating
    ** (UndefinedFunctionError) function :crypto.rand_bytes/1 is undefined or private. Did you mean one of:

          * rand_seed/0
          * rand_seed/1

        (crypto) :crypto.rand_bytes(20)
        (arc) lib/arc/transformations/convert.ex:30: Arc.Transformations.Convert.temp_path/0
        (arc) lib/arc/transformations/convert.ex:3: Arc.Transformations.Convert.apply/3
        (arc) lib/arc/actions/store.ex:54: Arc.Actions.Store.put_version/3
        (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
        (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
    Function: #Function<0.129232098/0 in Arc.Actions.Store.async_put_version/3>
        Args: []
    ** (EXIT from #PID<0.448.0>) evaluator process exited with reason: an exception was raised:
        ** (UndefinedFunctionError) function :crypto.rand_bytes/1 is undefined or private. Did you mean one of:

          * rand_seed/0
          * rand_seed/1

            (crypto) :crypto.rand_bytes(20)
            (arc) lib/arc/transformations/convert.ex:30: Arc.Transformations.Convert.temp_path/0
            (arc) lib/arc/transformations/convert.ex:3: Arc.Transformations.Convert.apply/3
            (arc) lib/arc/actions/store.ex:54: Arc.Actions.Store.put_version/3
            (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
            (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
            (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

**Comment by wintermeyer** [comment]
It seems to be this problem:
https://stackoverflow.com/questions/44927921/phoenix-started-throwing-undefinedfunctionerror-function-crypto-rand-bytes-1

@hendri-tobing I can't figure out how to fix it or to do a work around.

**Comment by hendri-tobing** [comment]
> It seems to be this problem:
> https://stackoverflow.com/questions/44927921/phoenix-started-throwing-undefinedfunctionerror-function-crypto-rand-bytes-1
> 

We can edit the arc library, from `:crypto.rand_bytes(20)` to `:crypto.strong_rand_bytes(20)`, then recompile the deps. 
<img width="800" alt="screen shot 2019-03-03 at 12 34 40" src="https://user-images.githubusercontent.com/11748187/53691481-aba90f80-3db1-11e9-9ad6-07265b00f6dc.png">

**Comment by wintermeyer** [comment]
I replaced these instances with the new code in production:

    vutuv1@bonaureus:~/Github/vutuv/deps$ grep -R "crypto.rand_bytes" *
    arc/lib/arc/transformations/convert.ex:    rand = Base.encode32(:crypto.rand_bytes(20))
    cowlib/src/cow_multipart.erl:	base64:encode(crypto:rand_bytes(48)).

It works! 🎉

@hendri-tobing What is the best way to actually commit this fix to the repo? Is there a good way or do we have to live with this till v2.0?

**Comment by wintermeyer** [comment]
@hendri-tobing Forget it. I just add a link into the README.md for this issue. The days of v1.1 are counted any ways.
