### ISSUE TITLE
Avatar

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#571]
Add an avatar to the `user` model. In v1.1 we used https://github.com/stavro/arc but I'm open for other solutions if they make more sense. The files should be stored locally on the file system of the server.

Please have a look at the v1.1 version how we populated the avatars in the sign_up process by looking up the email addresses at https://www.gravatar.com. Feel free to copy and paste that code or to reinvent the wheel.

**Comment by hendri-tobing** [comment]
I will create a PR for this issue later today.

**Comment by riverrun** [comment]
The avatar has been added to the user model. The remaining work is to add a task to fetch the image from gravatar - this will be handled in #611.
