### ISSUE TITLE
EmailAddress Scaffold

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#573]
A `user` has_many `email_addresses`. 

# Attributes

- user_id, :integer
- value, :string
- description, :string
- is_public, :boolean, default: true
- position, :integer

## Indexes

- value (unique)
- user_id

## Validations

- @required_fields ~w(value is_public user_id)
- The associated user has to be valid.
- value has to be a valid email address. But don't go overboard with this. A 99% validation is fine for now.

## Misc

- Within a `user` all `email_addresses` are always ordered by the `position`.
- `value` is auto downcased during create and update.

# Routing

They are nested under the `users` resource:
`/users/:slug/email_addresses`

# Form

- value, :string
- description, :string # Pulldown select with 'Work', 'Home' and a free field where people can enter they own text.
- is_public, :boolean, default: true

**Comment by riverrun** [comment]
Will every email address need to be verified? Do we want to add a `verified` attribute to the table?

**Comment by hendri-tobing** [comment]
> Will every email address need to be verified? Do we want to add a `verified` attribute to the table?

I think so, to minimize false email addresses and security reason.

**Comment by wintermeyer** [comment]
> > Will every email address need to be verified? Do we want to add a `verified` attribute to the table?
> I think so, to minimize false email addresses and security reason.

Yes, we do have to verify every new email address by sending one email to it and having the user clicking on the verification link. We already do it in v1.1. Otherwise I could add your email address to my account and you couldn't use it any more.
