### ISSUE TITLE
Posts

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#577]
# The Idea

More text than Twitter but less than Medium. With markdown as the language of choice to write articles and the possibility to add photos. 

## Different Levels of Length and Features

- New users can only write 140 character posts with no markdown (just auto linking URLs). 
- Next level users can write 280 characters.
- Next level users can use markdown features.
- Next level users can write 512 characters.
- Next level users can write 2048 characters.

The newest posts will show up on the profile page (at least an excerpt if it is a longer post) and old posts will be available at `/users/:slug/posts` which is an index page with pagination. Each single post will be available at `/users/:slug/posts/:id`

## Twitter Cards

If a post contains a URL than essential information of that page should be displayed below the post in the profile list (e.g. Twitter card info or HTML title if Twitter card is not available).

## Tags

A post has tags (e.g. PHP, Origami, Travel).

# Edit/Delete

Yes, posts can be edited after being submitted. And of course they can be deleted.

# Attributes

- :title, :string
- :body, :string
- :page_info_cache, :string # to store the content of Twitter cards, etc.
- :user_id, :integer
- :publicated_at # Timestamp from when on the post is published.
- :visibility_level, :string # Drop Down Select [public|just for followers|private]

**Comment by riverrun** [comment]
Working on this and finished the basic outline of it.

One question: what do we want the default `visibility_level` to be - public, private or just_followers?

**Comment by wintermeyer** [comment]
> One question: what do we want the default `visibility_level` to be - public, private or just_followers?

private

**Comment by wintermeyer** [comment]
Thinking of it: If it is set to private how can a potential new follower follow it?

**Comment by riverrun** [comment]
The 'Different Levels of Length and Features' should not be implemented at the moment. This feature is under review. For more information, see [this issue comment](https://github.com/vutuv/vutuv/pull/660#issuecomment-512119965).

**Comment by riverrun** [comment]
Mostly done in #660.

Still to do are the Twitter cards / HTML tite and restricting access to just a user's followers.

**Comment by riverrun** [comment]
Closing this issue - added separate issue regarding Twitter cards / HTML title.
