### ISSUE TITLE
Vutuv Context

### ISSUE THREAD

**Issue by hendri-tobing** [wintermeyer/vutuv#579]
Because Phauxth is using Phoenix Context for authentication/authorization, not the pure Phoenix Schema. We have a chance to use context or a pure schema. There are pros and cons. The pros we can map the data structure to be more clearly, since a context will contain one or several schemas that are very close. 

I don’t know the following items are appropriate or not for Vutuv Context design.

* Accounts
    * User (username/primary-email, password_hash, confirmed)
    * EmailAddress (value, description, is_public)
    * Role (admin, user, etc)
* Biographies
    * Profile (first_name, last_name, middlename, nickname, honorific_prefix, honorific_suffic, gender, birthday_day, birthday_monht, birthday_year, locale, avatar, active_slug, headline, noindex?, validated?)
    * PhoneNumber
    * Membership
    * URL
    * UserSkill
    * WorkExperience
* Sessions
    * Session (expired_at)
* Social
    * Post
    * Point
    * Badge
    * Vote
    * Share
    * Endorsement
    * Group
    * SocialMediaAccount
* Services
    * Company
    * RecruiterSubscription
    * JobPosting
    * Coupon
* Scheduler
    * Birthday
    * Work anniversary?

According to this article https://cloud.google.com/blog/products/gcp/12-best-practices-for-user-account, we can separate concept of user identity and account. All user information for authentication can be separated from user profile.

**Comment by wintermeyer** [comment]
@riverrun What do you think of this?

**Comment by hendri-tobing** [comment]
I just realized that @riverrun is the one who created the Phauxth 🥇 :D 

Such amazing work!

**Comment by riverrun** [comment]
I will add a few comments about the benefits of using Phoenix context modules, some alternatives and how I think we should work with them.

The contexts serve as an api to the data layer, and the collection of context modules and database (schema / table) modules work almost as a separate app. Making the data handling separate in this way can help make reasoning about the code, testing and refactoring easier.

There are two alternative ways of keeping the data handling separate - using umbrella apps and actually separating the apps. In both these cases, you would work with two, or more, separate apps (with umbrella apps, these apps are integrated to a certain extent) - VutuvDB and VutuvWeb, for example.

Having separate apps can keep all the different parts isolated, but it is not necessary. Whatever we decide to do, I think we need to agree to certain guidelines about how we call other parts of the app. For example, we should not need to call anything in the VutuvWeb namespace from the data layer, we should only call the data layer through the context modules, and we should not call Ecto directly from the view or controller layers.

In sum, if we agree that keeping the data layer separate from the other parts is useful, then those are the choices, and I would use the context module way. How we organize it is a separate question, but @hendri-tobing 's seems like a good start.

**Comment by wintermeyer** [comment]
I only have one though here: With 2.0 we start on a green field. This is THE chance to do it right. Of course we have to find the sweet spot between best-possible and doable (time and resource wise). But as fare as I understand it the best possible way wouldn't mean more work in this case.

**Comment by riverrun** [comment]
As of #588, we have the following structure:

* Accounts
    * User (email, password_hash, confirmed)
* Sessions
    * Session (expired_at)

I also added custom phoenix generator templates for the context and schema. Running `mix phx.gen.context` will now produce modules with specifications (`@spec`) and types for the schemas. In addition, the bang (`get_*!`) functions have been replaced with regular `get_*` functions. After running the context generator, you will need to edit the schema type - replacing `any` with the correct type.

**Comment by wintermeyer** [comment]
> I also added custom phoenix generator templates for the context and schema. Running `mix phx.gen.context` will now produce modules with specifications (`@spec`) and types for the schemas. In addition, the bang (`get_*!`) functions have been replaced with regular `get_*` functions. After running the context generator, you will need to edit the schema type - replacing `any` with the correct type.

Could you create a mini example of how to use it in the wiki or in the development document? For a new developer to read.

**Comment by hendri-tobing** [comment]
Thank you for the tooling and the installation of Phauxth. FYI, I am in progress to separate the email_address schema, so users are allowed to input many email addresses as well as can use their verified-email to login.

**Comment by riverrun** [comment]
I can add an example of using the context generators later today.

**Comment by hendri-tobing** [comment]
FYI, almost done the email schema, update login, verify email, and bamboo smtp configuration for development (and README.md). I am still testing since Pre-Commit doesn't allow me to commit, if the tests fail 😆

**Comment by hendri-tobing** [comment]
How to pass "don't commit to branch", even all tests are passed, @riverrun ? Is there something missed in my configuration file?

<img width="568" alt="Screen Shot 2019-03-20 at 07 17 16" src="https://user-images.githubusercontent.com/11748187/54650451-33488b00-4ae1-11e9-9abc-c152b6bdf286.png">

Thank you.

**Comment by riverrun** [comment]
Run `git checkout -b develop` and then try to commit.

The Don't commit to branch check is so that you don't commit changes to master.

**Comment by riverrun** [comment]
From the contexts mentioned in the original post, we have completed the User, Biographies and Sessions contexts. That leaves the following contexts to be done.

>     * Social
>       
>       * Post
>       * Point
>       * Badge
>       * Vote
>       * Share
>       * Endorsement
>       * Group
>       * SocialMediaAccount
> 
>     * Services
>       
>       * Company
>       * RecruiterSubscription
>       * JobPosting
>       * Coupon
> 
>     * Scheduler
>       
>       * Birthday
>       * Work anniversary?

Which ones of these do we want to prioritize? Are there any that we do not need?

**Comment by riverrun** [comment]
Closing in favor of #675
