### ISSUE TITLE
Gender should be optional

### ISSUE THREAD

**Issue by MarioRicalde** [wintermeyer/vutuv#581]
When working with #558 I noticed that we ask for gender from the get-go, and we offer three options (Male, Female & Diverse). Now that I'm working on #576 I see that we show it in Profile, and it makes me wonder as to the reason for the requirement.

I'm hoping that choosing Gender shouldn't affect the UX of a new sign-up, and if that's the case, I propose we remove it as a required field and instead we offer it as just another field they can feel **IF** they want to. Based on #220 it seems like we don't display it on the third option, but that comes as bad UX if that's the case for 2.0.

And one less thing to ask during Sign Up would lower the chances of a user thinking filling a long form is too much hassle.

Hope I make sense.

**Comment by wintermeyer** [comment]
> When working with #558 I noticed that we ask for gender from the get-go, and we offer three options (Male, Female & Diverse). Now that I'm working on #576 I see that we show it in Profile, and it makes me wonder as to the reason for the requirement.

My main reason: I want to address males as Mr. X and females with Mrs. X in an email. But because we live in 2019 we have to have the third option too. For inclusion and because it is the right thing to do.

Maybe it doesn't make a difference in the WebGUI. But we need the information.

> I'm hoping that choosing Gender shouldn't affect the UX of a new sign-up, and if that's the case, I propose we remove it as a required field and instead we offer it as just another field they can feel **IF** they want to.

We need to ask for it in the sign up to have the right greeting in the first email. It's one of the things I want to make better than the other players.

> And one less thing to ask during Sign Up would lower the chances of a user thinking filling a long form is too much hassle.

I know what you mean. I had the same idea and thought that we could make it a radio button with male or female as the default. By that we have a 50% chance that the user doesn't have to enter more data.

**Comment by MarioRicalde** [comment]
![image](https://user-images.githubusercontent.com/125900/53975825-5c255500-40cb-11e9-874f-79fc39ff7f1d.png)

I'm all in for the third option, as someone that has friends that would pick the third one. Kudos for that. However, I'm more focused on the need to ask the user to pick before they reach a screen where other personal information is asked. As gender should not be a big deal. 

I just created an account, and noticed that we're not using Mr. or Mrs. X - and I think that the absence of it is not a big deal, especially since I have not provided you with information that could change that, such as a PhD. What about, let's say, Doctors ? Wouldn't they be Dr. for both in English? In spanish we have distinction between genders, but in English they don't.

If it's about formality, we could show the full name in the email instead of prefixing my name with "Mr.". 

My suggestion is to move the gender selection one screen, right after the user clicks the confirmation email. That way those that don't agree with the three options can ommit to fill it and all is good. And if they choose to pick diverse show it instead of hiding it. If they gave us that piece of information, they want it to be seen at that point.

I see more positives than negatives at that point to remove Gender as a required field for Sign Up.

**Comment by wintermeyer** [comment]
> I just created an account, and noticed that we're not using Mr. or Mrs. X

Not in English. But in German. Here's an email I received today:

<img width="222" alt="bildschirmfoto 2019-03-07 um 19 46 02" src="https://user-images.githubusercontent.com/69770/53980959-f01a0f80-4111-11e9-9bce-7f83652d34c1.png">

So it's language dependent. In some languages it is ok to address somebody with the first name and others are more complicated.

> If it's about formality, we could show the full name in the email instead of prefixing my name with "Mr.".

It's about doing it right and sending a signal that we care.

I see your workflow point but this one is important for me. In German it makes a big difference if I address somebody correctly or not. I want the very first email to be as good as possible.

By the way: The signature changes depending on the weekday too. Wishing users a great weekend when it makes sense.

> I see more positives than negatives at that point to remove Gender as a required field for Sign Up.

I see your point and we might loose people over this but this one is dear to my heart.

In case people don't want their gender to be stored: It hasn't happened yet. At least I didn't get any feedback about this. And I did get feedback that it was unfair to have "male" as the default in the drop down select field. That's the reason that field doesn't have a default in v1.1. But I'm open to an improvement - that people can deactivate it - in version 2.1 for this.
