### ISSUE TITLE
Add pre commit and analysis (dialyzer) tools

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#582]
Add pre-commit hooks using the [pre-commit library](https://pre-commit.com/) to help us check that there are no compilation warnings, all the tests pass and that the code is properly formatted.

Also add [dialyxir](https://github.com/jeremyjh/dialyxir) so that we can use the Erlang static analysis tool dialyzer to analyze the code.

**Comment by wintermeyer** [comment]
Great idea. For the pre-commit library we have to update the `README.md` for developers too.
