### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#583]
We need to set up continuous integration support. Shall we go with travis, or do any of you have any other preferences?

**Comment by wintermeyer** [comment]
I’m good with Travis. Actually it should already work as soon as the config file is pushed.

**Comment by wintermeyer** [comment]
@riverrun Can you take care of this? I did set it up for v1 but I'm not sure if it was the best way possible. I just double checked: travis should work on master.

<img width="728" alt="Bildschirmfoto 2019-03-10 um 07 48 32" src="https://user-images.githubusercontent.com/69770/54081691-e9092200-4308-11e9-8812-530c693ca908.png">

**Comment by riverrun** [comment]
Ok. I'll look into it.

**Comment by riverrun** [comment]
Travis Github integration is in the middle of being updated at the moment - see [this link](https://docs.travis-ci.com/user/migrate/legacy-services-to-github-apps-migration-guide/) for more info.

**Comment by wintermeyer** [comment]
I tried to migrate it. But ended with this message:

<img width="671" alt="Bildschirmfoto 2019-03-12 um 08 48 02" src="https://user-images.githubusercontent.com/69770/54183120-96b03880-44a3-11e9-891e-3e815076aebf.png">

I guess we can wait till they automate it.

**Comment by riverrun** [comment]
Fixed in #588
