### ISSUE TITLE
Make sure that PRs are reviewed before merged

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#590]
I think we should encourage developers to get their pull requests reviewed as much as possible. It is another way to get valuable feedback and help prevent bugs.

There is more infomation about enabling this [here](https://help.github.com/en/articles/enabling-required-reviews-for-pull-requests).

**Comment by wintermeyer** [comment]
Good thinking!

<img width="788" alt="Bildschirmfoto 2019-03-14 um 07 34 46" src="https://user-images.githubusercontent.com/69770/54336197-b07c8780-462b-11e9-9d31-9b0899886149.png">
