### ISSUE TITLE
Syncing of php layouts & assets

### ISSUE THREAD

**Issue by xamiam** [wintermeyer/vutuv#594]
Currently the frontend layouts are based on php and client side scss compilation. The layouts are currently hosted at 

https://max-interactive.rocks/vutuv-2/

It would be great to set up a shared hosting so everyone has easy access to project files (html, svg, css).

**Comment by wintermeyer** [comment]
> It would be great to set up a shared hosting so everyone has easy access to project files (html, svg, css).

Have you tried to do this with Heroku?

**Comment by xamiam** [comment]
Yes, I just did. Works like a charm:

https://vutuv-layout.herokuapp.com/

I invited you via heroku.

**Comment by wintermeyer** [comment]
> I invited you via heroku.

Please invite @hendri-tobing and @riverrun too. After you finalized it we have to discuss how to set it up within the Phoenix project.

**Comment by wintermeyer** [comment]
@riverrun @hendri-tobing How do we tackle this best? @xamiam has no Phoenix background at all. So one of you has to use his PHP generated HTML and CSS to import it into the Phoenix project.

## The Problem

Because of web performance we probably have to have multiple sets of CSS. One for the sign up page, one for the profile page and maybe a generic one for other pages.

When ever possible we want to ship one HTML file with all the CSS and if needed JavaScript embedded. At least as long as that combined file is compressed less than 14 KB or 42 KB.

In case somebody doesn't know why 14 KB is important: Please ping me on that and I'll try to explain it.

**Comment by riverrun** [comment]
I can take care of adding the html and css to the project - then we can look at the optimization later. I will also do a bit of research about the optimization options.

**Comment by wintermeyer** [comment]
@riverrun Thank you!

@xamiam Please provide @riverrun with the Heroku access in case you haven't yet. Maybe you can also share some light what tools you used (SASS I guess?).

**Comment by xamiam** [comment]
Hey @riverrun, I added you as a collab in heroku a while ago. I am using SASS to compile a part of the bootstrap css framework and mix that with custom layout. Please get in touch if you have any questions or suggestions.

CC @wintermeyer

**Comment by riverrun** [comment]
A quick update: I will have a PR ready (to add this layour) later today - 26 March.

**Comment by riverrun** [comment]
@wintermeyer a question about shipping one small html file - how does updating to http2 change those calculations? Or are there reasons not to update to http2?

**Comment by wintermeyer** [comment]
> @wintermeyer a question about shipping one small html file - how does updating to http2 change those calculations? Or are there reasons not to update to http2?

It does change the calculation. But we don't have 100% coverage for HTTP/2 (many users with old feature phones and old browsers) and we don't have the resources to create two different solutions. So even while using HTTP/2 and HTTP/1.1 we are optimizing everything for HTTP/1.1 only.

**Comment by riverrun** [comment]
@wintermeyer understood.

The styling was merged in #598, so we can close this issue now.

I have opened #603 about reducing the size of the css, which we will need to do keep the size of the initial page down to 14 KB or 42 KB.
