### ISSUE TITLE
Fast, secure and less annoying

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#595]
While thinking about #558 I stumbled over the "Fast and secure business network" motto.

## Thoughts

- It's not just a "business network". It is a generic social network.
- Three adjectives always sound nicer.
- It doesn't hurt to put a smile on somebodies face.

## Motto

So I'm thinking about calling it **Fast, secure and less annoying** or **The Fast, Secure and Less Annoying Social Network**

But I'm not a native speaker. @riverrun: How does it sound for you?

It would translate nicely into German too which is a nice aspect.

How does everybody think about it?

**Comment by wintermeyer** [comment]
Second though: Maybe just "Fast and less annoying" and "The fast and less annoying social network"

I don't know how important the word "secure" is in this context.

**Comment by riverrun** [comment]
My initial thoughts are that "fast, secure and less annyoing" and "the fast and less annoying social network" both sound good.

It would be interesting to hear why you see it as a social network, rather than just a business network, and in what way it will be less annoying.

**Comment by wintermeyer** [comment]
> It would be interesting to hear why you see it as a social network, rather than just a business network, and in what way it will be less annoying.

IMO business network is a limitation. Of course it is a business network but not just that. With the new posting feature it will become a bit more Twitter/Facebook/Medium like. I'm not totally against "business network". I just want to discuss if "social network" might be the better term. 

**But there is no harm to change it form "business" to "social" later.**

**Comment by wintermeyer** [comment]
"fast, secure and less annoying" it is.
