### ISSUE TITLE
Login - just with primary email?

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#607]
This is a question about how we handle login. Do we allow login with any registered email, or do we restrict it to just the primary email?

**Comment by wintermeyer** [comment]
> This is a question about how we handle login. Do we allow login with any registered email, or do we restrict it to just the primary email?

Any of the registered emails. Because if people loose their job they might use their primary email address. But if they added their private email address they can still log in.

**Comment by riverrun** [comment]
Ok. I will work on that next.

**Comment by riverrun** [comment]
Fixed
