### ISSUE TITLE
Dialyzer, unknown_function :httpc

### ISSUE THREAD

**Issue by hendri-tobing** [wintermeyer/vutuv#608]
I am working on Profile's avatar, to get the default avatar from https://www.gravatar.com.

I am adding this functions to accounts.ex module
```
  defp get_gravatar(primary_email, userid) do
    hash = primary_email
      |> String.trim()
      |> String.downcase()
      |> :erlang.md5()
      |> Base.encode16(case: :lower)

    Application.ensure_all_started(:inets)
    Application.ensure_all_started(:ssl)

    img = 'https://www.gravatar.com/avatar/#{hash}?s=150&d=404'

    if {:ok, {status, header, body}} = :httpc.request(:get, {img, []}, [], []) do
      case status do
        {_, 404, 'Not Found'} -> nil
        {_, 200, 'OK'} ->
          content_type = find_content_type(header) |> to_string
          filextension = String.replace(content_type,"image/", "")
          filename = "original.#{filextension}"
          path = "#{Application.get_env(:vutuv, :storage_dir)}"<>"#{userid}/"
          File.write(path<>filename, body)
          _upload =  %{ file_name: filename, updated_at: NaiveDateTime.truncate(NaiveDateTime.utc_now, :second)}
        true -> nil
      end
    end
  end

  defp find_content_type(header) do
    Enum.reduce(header, fn {k, v}, acc ->
      if (k == 'Content-Type' or k == 'content-type'), do: v, else: acc
    end)
  end
```

Because the function needs a simple http request, I use :httpc, which is an Erlang built-in function. The above functions are working. 

However, dialyxir complains there is no :httpc function.

<img width="571" alt="Screen Shot 2019-04-13 at 16 58 49" src="https://user-images.githubusercontent.com/11748187/56078052-8a562d00-5e0d-11e9-9248-9e2d1c2b5b07.png">

How to overcome this issue? 

Thank you.

**Comment by riverrun** [comment]
For the time being, add `@dialyzer {:nowarn_function, get_gravatar: 2}` to the Accounts module. That suppresses the warning, and then we can work out why we are getting the warning later.
