### ISSUE TITLE
[QUESTION] Email address controllers

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#613]
This issue is just about clarifying how we want the email_address controllers to behave. I will outline my thoughts here, and then you can comment on them below.

## Routes

* index - lists all the email_addresses for a specific user (the current user)
* show - lists all the details for a specific email_address
* new / create - form to create a new email_address
    * this will need to include a function to request email confirmation
* edit / update - form to update an email_address
    * the user should not be able to update the `value` this way (updating the `value` needs to be done by deleting the email_address and creating a new one)

## Authorization

All the email_address controller routes should be protected. The current user should only be able to access his / her own email_address resources. None of the routes should be open to the public.

**Comment by wintermeyer** [comment]
I agree with everything. Maybe we should add a 404 with a specific error message for the edit/update. So that a user understands why he/she can not edit an email address.

**Comment by riverrun** [comment]
One more question - shall we nest the routes, so that the route would be, for example, `/users/1/email_addresses` instead of `/email_addresses`?

**Comment by wintermeyer** [comment]
Nesting this route seems to make the most sense. This is what I as a user would expect.

**Comment by riverrun** [comment]
All fixed in #615
