### ISSUE TITLE
No JavaScript

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#614]
The version 1.0 doesn't use JavaScript. This is mainly because of https://www.internet.org/ which delivers vutuv to it's users for free. This is actually a big deal because LinkedIn is not on that platform and internet.org delivers internet to many people who wouldn't have it otherwise. We do have quite a few vutuv users from internet.org

In version 2.x I'd like to integrate a non JavaScript version and a version which uses JavaScript to make a nicer GUI. But because we can not create both worlds in the 2.0 version we have to go with the non JavaScript version and implement the JavaScript version for 2.1.

We can use cookies. Just not JavaScript.

I remember that in version 1.0 this was easier said than done because the default Phoenix scaffolding uses JavaScript.

@riverrun and @hendri-tobing: Please share your thoughts.

**Comment by hendri-tobing** [comment]
The purpose of a non-JavaScript version is for the fast performance. The purpose of the JavaScript version is for a nicer GUI. Which one will give us more benefits/users? I agree in version 2.1, we can use JavaScript as optimum as possible to allow a nice GUI and also relatively still fast application.

**Comment by riverrun** [comment]
The only javascript currently being used is from the Phoenix HTML application, and it is used with forms.

When removing this javascript, delete actions might not work properly, and there might be other issues related to form handling.

**Comment by riverrun** [comment]
The problem with (and solution for) using the delete method in forms is outlined in [this SO question](https://stackoverflow.com/questions/28164132/how-to-patch-or-delete-from-a-form-without-javascript).

@wintermeyer do you know if this kind of workaround works with https://www.internet.org/?

**Comment by wintermeyer** [comment]
> The problem with (and solution for) using the delete method in forms is outlined in [this SO question](https://stackoverflow.com/questions/28164132/how-to-patch-or-delete-from-a-form-without-javascript).
> 
> @wintermeyer do you know if this kind of workaround works with https://www.internet.org/?

I do not know. But `<input name="_method" type="hidden" value="patch" />` seems to be really simple. This should AFAIK work. But please have a look into version 1 to see who it was solved in it.

**Comment by riverrun** [comment]
@wintermeyer what is the best commit to look at for version 1? I looked at the [commit before the initial work was started for v2](https://github.com/vutuv/vutuv/commit/41fcb9e87da67c12adde3671d9d40d78a0f339cc). Is this the best one?

**Comment by wintermeyer** [comment]
https://github.com/vutuv/vutuv/tree/v1.1

**Comment by riverrun** [comment]
Fixed in #634
