### ISSUE TITLE
Use one-time passwords for email verification

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#616]
# The Problem

Users of the https://www.internet.org platform can not enter URLs. They open a special application which hosts a web browser which opens on a default page. From there on users can click on websites within the internet.org universe. So they click on the vutuv.de button but they can not enter https://www.vutuv.de

So our default "click on this link to verify your email address" doesn't work for them. They can not click on that link.

In version 1.0 we checked if an account was created on the internet.org platform:

> **Detecting Requests**
All requests that pass through the Internet.org proxy will contain X-IORG-FBS field (always set to true). It's enough to just check for its existence inside the header.
https://developers.facebook.com/docs/internet-org/platform-technical-guidelines/

If that was a case we send the user a 6 (IMO) digit number as a PIN which he/she could enter anything. We don't want them to enter a 20 characters long alpha numeric string here. They have to have a chance to read their email and remember the PIN to open the internet.org application and using the PIN there on the vutuv.de page. Most of those users use feature phones with no cut and paste functionality.

# Solution

I don't know what the best solution for this problem is. If we don't verify the email address for those users a couple of them will create bogus accounts which we do not want. So we have to find a way to verify the email addresses.

**Comment by riverrun** [comment]
About the 6-digit PIN, we can use one-time passwords (TOTP) for this - this will mean that the users will have about 60-90 seconds to input the PIN, after which the PIN expires.

**Comment by wintermeyer** [comment]
TOTP is a great idea. We just need to give the users more time. More something like 5 minutes. 

And we have to find a solution for the accounts with not working email addresses. That happens every day (I have no idea why so many people have a hard time to enter a correct email address). We should find a solution to auto delete the accounts when the user doesn’t log in within x minutes.

**Comment by riverrun** [comment]
It seems that it is now becoming more common for one-time passwords to be used for email verification (password resetting). We can replace the current method by using time-based one-time passwords (TOTP) for all email verification.
