### ISSUE TITLE
Phone number scaffold 

### ISSUE THREAD

**Issue by hendri-tobing** [wintermeyer/vutuv#618]
Phone number scaffold on Biographies Context. 

Based on Vutuv version 1, it contains the following fields:
field :type, :string
field :value, :string

**Comment by riverrun** [comment]
Will users be able to log in using the phone number?

**Comment by wintermeyer** [comment]
That is a really good question. Long term: Yes. Short term: We have enough other things to do. I don’t want to open the text message box now.

**Comment by riverrun** [comment]
Fixed in #619
