### ISSUE TITLE
email address format validation

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#620]
It is unbelievable how many new users don't enter their email address correctly. Mostly simple typos like: "X yz <xyz@gmail>" (missing .com at the end). It would help to offer a simple email address validation which uses a regular expression. I know that a proper regular expression for email addresses is easier said than done. But an 80% solution would make a big difference here.

@riverrun Please close this issue in case you are already doing this. I just walked through some error emails and created this issue because of those errors in version 1 of vutuv.

**Comment by riverrun** [comment]
Could you provide some examples of typos? Then we can test some of these.

I also need to open an issue about running a server that will delete emails that are not confirmed / verified (or that will schedule a reminder to the user before deleting them).

**Comment by wintermeyer** [comment]
Believe it or not these are all real example of the last couple of days:

- iviwekulati@gmail.com2002
- victoriathankgod7@gmaill.com
- http//@bolomo.com
- frankdaud234@gmail
- mudassir.com@pk
- ricoandrew592@gmail

**Comment by wintermeyer** [comment]
Just an idea for the future: We could use `<meta http-equiv="refresh" content="3; URL=https://www.vutuv.de/foobar">` to auto refresh the status page to give the user an update about his/her email. So when we get an SMTP error we could display it there. Of course not all browsers will auto refresh but again 80% is better than nothing.

**Comment by riverrun** [comment]
We already check the email format on the backend, but we probably should make sure that we check it in the form as well (using the [`email` input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email) - together with `pattern`). We also need to make the email formatting regex that we are using stricter / more accurate, although according to the [emailregex site](https://emailregex.com), it might be impractical to make it 100% accurate.

Based on the pages cited above and [this page which outlines the email syntax rules](https://help.returnpath.com/hc/en-us/articles/220560587-What-are-the-rules-for-email-address-syntax-), we will use one of the following two regexes (the second one is stricter with regard to the top-level domain):

```
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-\.]+\.[a-zA-Z0-9-]+$/
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9-\.]+\.[a-zA-Z]{2,}$/
```

**Comment by riverrun** [comment]
Added in #628
