### ISSUE TITLE
Skill, UserSkill, Endorsement Scaffold

### ISSUE THREAD

**Issue by hendri-tobing** [wintermeyer/vutuv#621]
Skill, UserSkill, Endorsement Scaffold.

Based on Vutuv V1.1

skills schema:
    field :name, :string
    field :downcase_name, :string
    field :slug, :string
    field :description, :string
    field :url, :string
    has_many :user_skills

user_skills schema:
   belongs_to :user/:profile
   belongs_to :skill
   has_many :endorsements

endorsements schema:
   belongs_to: User/Profile
   belongs_to: UserSkill

**Comment by wintermeyer** [comment]
Maybe we should rename this to `tags`. A `tag` could be used for all sorts of things. One could tag a post too. The `skill` idea was in retrospect too ambitious and didn't pay out.

`endorsements` are still good.

Keep it simple. Please do not just copy v1 functionality 1:1.

**Comment by wintermeyer** [comment]
And please do not copy the translation idea from v1. That was a total disaster. A good idea but for that we'd need a lot of funding to be implemented. Keep it simple and don't do translations of `tags`.

**Comment by riverrun** [comment]
Fixed in #624
