### ISSUE TITLE
vCard by email address hash

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#622]
Think https://en.gravatar.com but for vCard information. So somebody could enter his/her email address on a website and that website fetches the vCard with a GET request and a hash of the email address.

Of course users have to have a check box to opt-out of this functionality.

Please comment in this issue if you can find of scenarios where is would become an evil feature. I think it could become as powerful as Gravatar but the information is more sensitive.

**Comment by hendri-tobing** [comment]
This is interesting idea. Agree, it will be very powerful feature. It can be one of the best feature of Vutuv. However, we must be careful with the sensitive information. Bad guys can misuse those information.

Is it possible to let users approve or at least know that somebody or a system fetches their vCard?

Or we can limit only authorized systems or persons can fetch those information.

Also how can EU's GDPR "right to be forgotten" be implemented in this feature?

**Comment by wintermeyer** [comment]
> Is it possible to let users approve or at least know that somebody or a system fetches their vCard?

The feature wouldn't make any sense if every request would have to be approved by the user. That would take too much time.

People who use vutuv want to share information. Otherwise they wouldn't use it. So the default could be 'export of vcard is ok'. Of course there has to be an opt-out functionality. And people who don't want to be listed in search engines should have a no as a default too.

> Also how can EU's GDPR "right to be forgotten" be implemented in this feature?

Every user can delete his/her account any time.

**Comment by riverrun** [comment]
@wintermeyer where will they fetch the vCard from? From Vutuv?

**Comment by wintermeyer** [comment]
> @wintermeyer where will they fetch the vCard from? From Vutuv?

@riverrun The normal user can fetch the vCard from each users profile page. Power users or other services should be able to fetch the vCard via an API call or just by adding `.vcard` to the profile URL.

![vcard](https://user-images.githubusercontent.com/69770/58486656-8a647f00-8166-11e9-9c3d-3eab6c64e4b5.gif)

**Comment by riverrun** [comment]
I see in version 1, we are creating the vcard based on the information we have. Do we want to do this in version 2? Would there be an option for users to upload their vcards?

**Comment by wintermeyer** [comment]
Uploading a vCard is a great idea. I’ve never thought about the possibility. 

Let’s do downloading a vCard first. Fill it with the information we have. 

But let’s come back to the upload in the future. It would be a great way to inject data for new accounts.

**Comment by riverrun** [comment]
Related to [Hendri's earlier comment](https://github.com/vutuv/vutuv/issues/622#issuecomment-493802302) and #567, here is a link to an [article about the dangers of using the gravatar method](https://fly.io/articles/how-gravatar-hurts-your-visitors/), and how it can be improved.

**Comment by riverrun** [comment]
Most of the work on this has been done in #670. There still remains the question as to how a user can request the vcard - shall we use a slug or a hash of the email address, etc.?

**Comment by wintermeyer** [comment]
- There should be a link on the user's profile page which everybody can use to just click on to download the vcard.
- There should be an API which uses the MD5 sum of an email address to deliver the vcard.

**Comment by riverrun** [comment]
The link on the user's profile page is already done.

We just need to add the 'request-by-hash' functionality.

**Comment by riverrun** [comment]
@wintermeyer a quick question about the route for the vcard:

Currently, the route is set to `/users/user.slug/vcard`. Shall we change this to `/vcard/email_address_hash`?

**Comment by riverrun** [comment]
Closing this issue. We are still undecided as to what the route should be, so we are keeping it as it is - `/api/v2/users/user.slug/vcard` for the moment.
