### ISSUE TITLE
User (user profile) routes

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#626]
At the moment, the user data and user profile data are separated. I think that we probably do not need to have separate user profile routes because the user profile data can be accessed from the user routes. Any thoughts?

Next, a question about authorization. In the table below, the routes are listed together with who can access them (any user includes users that are not logged in):

| Route action | Can access |
| ------------- | ------------- |
| index | any user |
| new | any user |
| create | any user |
| show | any user |
| edit | only current user's page |
| update | only current user's page |
| delete | only current user's page |

Does this outline look ok?

**Comment by wintermeyer** [comment]
> At the moment, the user data and user profile data are separated. I think that we probably do not need to have separate user profile routes because the user profile data can be accessed from the user routes. Any thoughts?

I agree.

> Next, a question about authorization. In the table below, the routes are listed together with who can access them (any user includes users that are not logged in):
> 
> Route action	Can access
> index	any user
> new	any user
> create	any user
> show	any user
> edit	only current user's page
> update	only current user's page
> delete	only current user's page
> Does this outline look ok?

Yes, it does.

One problem: Support. What if an admin/supporter needs to change data (for what ever reason)? Of course this could always be done direct in the database but that is a way I'd like to avoid if possible. On the other hand I don't want to waste a lot of time on this (yet). So in case we can find a solution for this which can be implemented fast than that would be perfect. If not then let's go with the above solution and revisit this in version 2.1.
