### ISSUE TITLE
Title case or sentence case

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#630]
While working on #629, I noticed that some headings are written with all capital letters (title case) and some are written with just the first word capitalized (sentence case).

I think it would be useful to decide which one we want to use and stick with it. That will make the site look more professional.

Personally, I don't have a strong opinion on this matter, but I do prefer sentence case.

More information about the differences can be found [Why letter casing is important](https://uxplanet.org/why-letter-casing-is-important-to-consider-during-design-decisions-50402acd0a4e) and [Making a case for letter case](https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98).

**Comment by wintermeyer** [comment]
Good catch! Let's go with sentence case.

**Comment by riverrun** [comment]
The templates now use sentence case. I need to add a short note about this to the CONTRIBUTING guide, and then we can close this issue.

**Comment by riverrun** [comment]
Fixed in #634
