### ISSUE TITLE
locale

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#646]
Currently the `locale` of a `user` is set to `nil`. In v1 we used the HTTP header to fetch the locale. Of course this could be wrong but in 95% of all cases it is a very good value for this. But users have to be able to override it.

Problem: We do not support all languages. In the beginning just `de` and `en`. We have to find a mapping where `en` is the default language if the `locale` is not yet supported.

**Comment by riverrun** [comment]
What do we use the locale for?

**Comment by wintermeyer** [comment]
e.g. to send localized emails to the users.

**Comment by riverrun** [comment]
Ok. Got it.
