### ISSUE TITLE
List of all users

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#659]
We need a list of all users. That list has to have a pagination. It is like a phone book. Each entry is linked to the user profile. The list itself is linked in the footer.

**Important:** The links to profiles of users who don't want to be listed in search engines have to be no-follow.

**Comment by riverrun** [comment]
The following parts of this issue have already been implemented:

* list users route with links to the users' profiles
* a link to the list in the footer (this is in PR #660)

We still need to implement the following:

* pagination
* no-follow links for users who do not want their profiles indexed
