### ISSUE TITLE
System to write emails to all users

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#662]
We need a system to be able to write emails to all users. This issue is just the start to figure out exactly how to form it.

The email contains of:
- Subject
- Body

The process:
- An email gets written by a person who has the access right to do this.
- The email gets stored as a `draft`. That version can be changed multiple times.
- The email gets sets send. After that the email text can not be changed afterwords.
- There should be two ways of sending an email:
  - Send it now!
  - Send it when it is convenient for the user. That would be the time the user set for his/her account.

Misc:
- We need a log. When was what send.

**Comment by riverrun** [comment]
Regarding roles / permissions, here is a [useful link](https://stackoverflow.com/questions/13102872/better-way-to-represent-user-roles-in-database) which goes over various options and their pros and cons.

I think that we can just add an `is_admin` column to start off with, and then we can add more functionality later.

**Comment by wintermeyer** [comment]
> I think that we can just add an `is_admin` column to start off with, and then we can add more functionality later.

I agree.

**Comment by riverrun** [comment]
Most of the work (the foundations of this functionality) was completed in #687.

Closing this issue - its progress can be followed in the three remaining issues - #688, #689 and #690.
