### ISSUE TITLE
[Question] Free Software

### ISSUE THREAD

**Issue by ghbjklhv1** [wintermeyer/vutuv#665]
**Question**: Is Vutuv [free/libre](https://www.wikipedia.org/wiki/Free_software) software?

I've seen projects too many times claim "open source" and then keep some snippets non-free.
I wanted to make sure Vutuv  isn't just open-source-y but also completely [free/libre](https://www.wikipedia.org/wiki/Free_software) software.

**Comment by wintermeyer** [comment]
It is 100% open-source. MIT license.
