### ISSUE TITLE
Need to implement for version 2.0

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#675]
The following models are in version 1.1, but have not been implemented in version 2.0 yet.

* address (physical address)
* group
* job_posting
* job_posting_tag
* membership
* recruiter_package
* recruiter_subscription
* search_query
* social_media_account
* user_tag_endorsement
* work_experience

Are all of these necessary? Is there anything else that needs to be added to this list?

**Comment by wintermeyer** [comment]
What we need:

- address (physical address)
- social_media_account
- user_tag_endorsement (some kind of)
- work_experience

**Comment by riverrun** [comment]
Quick update: working on address and social_media_account now.
