### ISSUE TITLE
Add user_tag routes

### ISSUE THREAD

**Issue by riverrun** [wintermeyer/vutuv#680]
In version 1.1, it seems that there were routes for index, new, create, show and delete for the user_tags  - user_tags were also displayed, as a card, in the user's profile page.

In version 2, do we want the same routes for user_tags?

**Comment by wintermeyer** [comment]
> In version 2, do we want the same routes for user_tags?

We don't need those routes for the HTML. I'm not sure if we need them for the JSON API. An API client has to be able to do an index, new, create, show and delete. But maybe this can be done by nesting it with the user.

**Comment by riverrun** [comment]
For user_tags, I think we might need new, create and delete routes - so that a user can create and delete user_tags. Alternatively, we could let the user create / delete user_tags in the user edit / update page - where they edit / update other profile information.

For listing user_tags, we can list them in the 'card' in the user page.

Any thoughts?

**Comment by wintermeyer** [comment]
I like the idea of just having new, create and delete for user_tags and list them in the 'card'.

**Comment by riverrun** [comment]
Added in #681
