### ISSUE TITLE
Feature Request: Social Media Entries for Mastodon and Matrix

### ISSUE THREAD

**Issue by vsatmydynipnet** [wintermeyer/vutuv#706]
While testing vutuv I found out that one is unable to enter his Mastodon and Matrix address in the social entries and only the big data miners are listed.

**Comment by wintermeyer** [comment]
We are currently in the process of finishing the next version of vutuv. So we do not open any new feature requests for the old version right now. 

I can not tell you when the new version is going online. But if you are interested in the process: Have a look into our repository. It is a very open process.

For now I close this issue.

**Comment by linux-lukas** [comment]
In addition to Mastodon and Matrix, Pixelfed, Hubzilla, Friendca and other Fediverse services would also make sense in my eyes.
