### ISSUE TITLE
A non default slug should be redirected to the default slug

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#73]
If a user has different slugs for his/her account all slugs should redirect to the default slug. The proper HTTP error code is a bit tricky. Doing a HTTP 302 (Moved Temporarily) is kind of misleading (because most times it is not temporarily) but HTTP 301 (Permanent Redirect). 

I like the following approach best:
- If the last update to the slugs is less than 4 weeks ago we'll do a 302.
- Otherwise we do a 301.

That gives the user some time to rethink his choices.

**Comment by cjfreeze** [comment]
The solution I chose was to redirect non-default slugs to user#show on the default slug. Simply changing the slug on whatever path the user was on would require rebuilding the url from its components and isn't natively supported by phoenix path_helpers.
