### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by JoelAmey** [wintermeyer/vutuv#743]
I registered for an account for the first time and checked my email for the verification but I never received one. I then registered again for an account and hit the error page. I prefer signal or metrix as a way to verify accounts as email and phone numbers are not private or encrypted. Also emails are ineffective as they do not behave like chats where you can have a cohesive back and forward of messages.

**Comment by wintermeyer** [comment]
> I registered for an account for the first time and checked my email for the verification but I never received one.

Did you check your spam folder? I just want to be sure that this is not a spam related issue.

> I prefer signal or metrix as a way to verify accounts as email and phone numbers are not private or encrypted. 

Truth be told: I have never thought about using a chat application for this. Never came to my mind. You might be on something here. This will not be achieved soon but I'll keep it in the back of my head.

**Comment by JoelAmey** [comment]
Well I'm touched that you replied so instantaneously and personally.

I'm on a journey decolonising my digital life and personal environment, as
in deprofitising my life or degoogling.
I hope that your platform can replace linkedin, RobBraxPrivacyGuy on YT
says it is worse than FB for privacy, although excellent ethics.
I misspelt matrix.org there are also other private options worth exploring.

I checked ALL my folders, sorry I should have said in the post.

**Comment by wintermeyer** [comment]
>  I hope that your platform can replace linkedin, RobBraxPrivacyGuy on YT says it is worse than FB for privacy, although excellent ethics.

Joel, vutuv is not on the same level as LinkedIn or other social networks right now. Has never been. It is a pity but I have never been able to find funding without selling my soul. That's the reason the project is in hibernation mode right now. But issues and messages like yours wake me up every now and then. I really would like to improve vutuv. 

I close this issue but keep it in the back of my head. Don't expect anything soon but I will try to make something happen in 2023.
