### ISSUE TITLE
Link verification

### ISSUE THREAD

**Issue by linux-lukas** [wintermeyer/vutuv#745]
### A. Problem / Goal

Verification of links is essential. One should be given the opportunity to do this oneself. 

The goal would be to implement a link verification facility in vutuv.

### B. Solution 

Implementing a workaround to verify using rel="me" attribute.

Example: 

A person refers to their blog with a link in their Vutuv profile. The verification is done by having a backlink to the blog - in the following scheme: 
<a rel="me" href="https://blog.domain.tld">blog</a>.

### C. Alternatives
None.

**Comment by wintermeyer** [comment]
A backlink is impossible for many users. If they set a link to their employer they can not put a backlink on that page.

I see your point but close the issue for now. I have to think more about it.
