### ISSUE TITLE
Basic User Scaffold

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#8]
Let's start with a basic `user` scaffold (plural `users`) with the following attributes:
- first_name
- last_name
- middlename
- nickname
- honorific_prefix
- honorific_suffix
- gender
- birthdate

We can add additional stuff step by step.

**Comment by oliverandrich** [comment]
nickname will also be used for authentication purposes, correct?

**Comment by wintermeyer** [comment]
No. People can login via magic links by e-mail or via LinkedIn, Twitter or Facebook Oauth.
