### ISSUE TITLE
Accent marks create problems in user#new

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#85]
José Valim would have a hard time to create an account. I guess it's because of the "é" and the `slug`. Best solution would be to convert the "é" into an "e". If that's too much work any non validating character in the `slug` should be removed.

![bildschirmfoto 2016-08-02 um 11 23 06](https://cloud.githubusercontent.com/assets/69770/17323827/e541fbee-58a3-11e6-8c09-d515413cb230.png)

**Comment by cjfreeze** [comment]
Are you okay with having accented characters in slugs? The error here is simply the default slug doesn't fit the regex in the validation. I can either un-accent all characters in the changeset or I can change the validation to allow accented characters.

**Comment by wintermeyer** [comment]
hmmm... having accented characters in slugs is an interesting idea. I haven't even thought about that possibility. But I'm chicken out for that right now. We are heading for old devises and I'm not sure if every devise/browser will show it correctly and many people will have problems to enter it with their keyboard. So for today: No. But I'll keep it in mind for the future.
