### ISSUE TITLE
Cleanup pipe_through :browser in router.ex

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#86]
In the `router.ex` file there are the following lines:

```
scope "/", Vutuv do
  pipe_through :browser
  [...]
  resources "/users", UserController, param: "slug" do
    pipe_through [:browser, :user_pipe]
  [...]
  pipe_through :browser
```

Is it possible that `pipe_through :browser` is a duplicate and/or that some refactoring would make sense here?

**Comment by cjfreeze** [comment]
Yes. I had a brief moment of forgetfulness when coding this up. The misuse of pipe_through was actually causing #84. All fixed now though.
