### ISSUE TITLE
URL scaffold

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#87]
A user has many `urls` which are nested under `/users/:slug/urls/`.
# Attributes
- `value`:string
- `description`:string
# Validations

`value` has to have a valid URL which starts with `http://` or `https://`. If a user enters a URL without the `http:` part the system should automatically add `http://` to it.

**Comment by cjfreeze** [comment]
Urls will be things such as a business website, personal blog, or even github page, correct?

**Comment by wintermeyer** [comment]
Correct.
