### ISSUE TITLE
Unknown column 'u0.administrator' in 'field list'

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#93]
http://localhost:4000/ leads to this error:

![bildschirmfoto 2016-08-04 um 14 46 41](https://cloud.githubusercontent.com/assets/69770/17402219/56fe46c0-5a52-11e6-9b1e-147654bf5fc0.png)

**Comment by cjfreeze** [comment]
Try mix ecto.reset. A typo was made in one of the migrations.

**Comment by cjfreeze** [comment]
Was able to reproduce the issue and solve it with mix ecto.reset.
