### ISSUE TITLE
Replace German Umlaute in slug

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#96]
German Umlaute in the automatically generated `slug` should be replaced by the following pattern:

ü = ue
Ü = Ue
ä = ae
Ä = Ae
ö = oe
Ö = Oe
ß = ss

Probably https://github.com/h4cc/slugger is the best solution for this.

A real word example:
## Karl-Heinz Müller

first_name: Karl-Heinz
last_name: Müller
slug: karl-heinz.mueller

**Comment by cjfreeze** [comment]
We might consider using this [library](https://github.com/h4cc/slugger).
