### ISSUE TITLE
Structured Data - Schema.org

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#98]
Adding https://developers.google.com/search/docs/data-types/social-profile-links to the HTML of `users#show`. http://schema.org/Person

**Comment by cjfreeze** [comment]
I have done what I think you wanted, but let me know if there was a miscommunication.

**Comment by cjfreeze** [comment]
From b250e24:

> ...The URL field is currently not used, as we do not have a way for the
> user to specify their "personal" website. We might consider adding
> this later on.
