### ISSUE TITLE
Login/Register via Facebook

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/vutuv#99]
If a user already has a Facebook account he/she can use this account to register and login to his/her vutuv account.

**Comment by cjfreeze** [comment]
Note that currently, the only data from facebook added is first and last name. I have created another issue #143 for the expansion of the facebook login system.
Additionally, Note that in order for the login by facebook feature to work, you need the following line in your hosts file:
`127.0.0.1 test.vutuv.de`

you will also still need to append :4000 to the end of the url. So an example url would like like this:
`http://test.vutuv.de:4000/`
